import { randomBytes } from "node:crypto";
import { chmod, readFile, rm, writeFile } from "node:fs/promises";
import { isAbsolute, join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

import { PACKAGED_BUILD_KEY } from "@crustjs/utils/artifacts";
import { runProcess } from "@crustjs/utils/process";

import {
	type BuildRunner,
	bunCompileTarget,
	resolveBunBuildRunner,
	resolveDenoBuildRunner,
} from "./compilers.ts";
import type { BunTarget, DenoTarget } from "./targets.ts";

export function toBunEnvFileArgs(envFiles: readonly string[]): string[] {
	return envFiles.flatMap((envFile) => ["--env-file", envFile]);
}

/**
 * Module source the generated driver imports for a `crust.bunPlugins` specifier.
 *
 * Paths become file URLs resolved against the project; bare specifiers are
 * imported as written so they resolve from the project's own node_modules.
 */
export function resolveBunPluginSource(specifier: string, cwd: string): string {
	return specifier.startsWith(".") || isAbsolute(specifier)
		? pathToFileURL(resolve(cwd, specifier)).href
		: specifier;
}

/**
 * Marks every Bun/Node bundle crust produces so `resolveArtifactDir` (core)
 * can tell a staged bundle from source at runtime. Not a `PUBLIC_*` variable:
 * it is internal to crust, never user-set. Deno compile has no define, but
 * standalone Deno binaries are detected directly.
 */
const CRUST_BUILD_DEFINE = { "process.env.CRUST_INTERNAL_BUILD": '"1"' } as const;
// The value keeps its quotes so bun inlines a string literal, not a number.
const CRUST_BUILD_DEFINE_ARG = 'process.env.CRUST_INTERNAL_BUILD="1"';

type BunPluginDriverBuild = {
	entrypoints: [string];
	minify: boolean;
	env: "PUBLIC_*";
} & (
	| { target: "bun"; compile: { target: string; outfile: string; autoloadBunfig: false } }
	| { target: "bun" | "node"; format: "esm" }
);

export type BunPluginDriverOptions = {
	plugins: Array<{ specifier: string; source: string }>;
	build: BunPluginDriverBuild;
	outfile: string;
};

/**
 * Script that runs `Bun.build` with the project's bundler plugins.
 *
 * `bun build` has no plugin flag, so plugins are loaded by a generated script
 * placed in the project root (project module resolution) and run with the
 * same runner as the CLI path. Every value is embedded via JSON.stringify.
 */
export function createBunPluginDriverScript(options: BunPluginDriverOptions): string {
	return `// Generated by crust build for crust.bunPlugins; deleted when the build finishes.
const options = ${JSON.stringify(options)};
const plugins = [];
for (const { specifier, source } of options.plugins) {
	let plugin;
	try {
		plugin = (await import(source)).default;
	} catch (error) {
		// Bun names this (soon deleted) driver as the importer; the project root is the useful location.
		const message = (error instanceof Error ? error.message : String(error)).replace(\` imported from \${import.meta.path}\`, "");
		console.error(\`crust.bunPlugins entry \${specifier} could not be imported from \${process.cwd()}: \${message}\`);
		process.exit(1);
	}
	if (typeof plugin !== "object" || plugin === null || typeof plugin.name !== "string" || typeof plugin.setup !== "function") {
		console.error(\`crust.bunPlugins entry \${specifier} must default-export a Bun bundler plugin ({ name, setup }). Wrap a plugin factory in a module that default-exports the created plugin.\`);
		process.exit(1);
	}
	plugins.push(plugin);
}
const result = await Bun.build({ ...options.build, define: ${JSON.stringify(CRUST_BUILD_DEFINE)}, plugins, throw: false });
if (!result.success) {
	for (const log of result.logs) console.error(log);
	process.exit(1);
}
if (!options.build.compile) {
	if (result.outputs.length !== 1) {
		// Same refusal as \`bun build --outfile\`: a file-type asset import yields entry + asset.
		console.error("error: cannot write multiple output files without an output directory");
		process.exit(1);
	}
	await Bun.write(options.outfile, result.outputs[0]);
}
`;
}

async function runBunPluginDriver(
	build: BunPluginDriverBuild,
	outfilePath: string,
	bunPlugins: readonly string[],
	envFiles: readonly string[],
	cwd: string,
	runner: BuildRunner,
): Promise<void> {
	const driverPath = join(cwd, `.crust-build-${randomBytes(6).toString("hex")}.ts`);
	await writeFile(
		driverPath,
		createBunPluginDriverScript({
			plugins: bunPlugins.map((specifier) => ({
				specifier,
				source: resolveBunPluginSource(specifier, cwd),
			})),
			build,
			outfile: outfilePath,
		}),
	);
	try {
		// The runtime loads env files before the script runs, so `env: "PUBLIC_*"`
		// inlines the same values as the CLI path's --env-file/--env flags.
		await runBuildProcess(runner, [...toBunEnvFileArgs(envFiles), driverPath], outfilePath, cwd);
	} finally {
		await rm(driverPath, { force: true });
	}
}

/**
 * Compile a single entry file to a standalone executable.
 *
 * Uses `bun build --compile` as a subprocess so the standalone compiler runs
 * in Bun's CLI process rather than inside the current Crust runtime.
 * This avoids in-process compiler issues seen on some host/target
 * combinations while still supporting env-file loading natively.
 *
 * @param entryPath - Absolute path to the entry file
 * @param outfilePath - Absolute path to the output binary
 * @param minify - Whether to enable minification
 * @param target - Bun compile target
 * @param envFiles - Optional env files to load during build
 * @param bunPlugins - Bun bundler plugin specifiers; when present the build
 *   runs through the generated `Bun.build` driver instead of `bun build`
 * @param runner - The selected Bun compiler (`resolveBinaryCompiler`)
 * @throws {Error} If the build fails
 */
export async function execBuild(
	entryPath: string,
	outfilePath: string,
	minify: boolean,
	target: BunTarget,
	envFiles: readonly string[],
	cwd: string,
	bunPlugins: readonly string[] = [],
	runner: BuildRunner = resolveBunBuildRunner(),
): Promise<void> {
	const compileTarget = bunCompileTarget(target, runner);
	if (bunPlugins.length > 0) {
		await runBunPluginDriver(
			{
				entrypoints: [entryPath],
				minify,
				env: "PUBLIC_*",
				target: "bun",
				compile: {
					target: compileTarget,
					outfile: outfilePath,
					autoloadBunfig: false,
				},
			},
			outfilePath,
			bunPlugins,
			envFiles,
			cwd,
			runner,
		);
		return;
	}
	const args = createBunCompileArgs(entryPath, outfilePath, minify, compileTarget, envFiles);
	await runBuildProcess(runner, args, outfilePath, cwd);
}

export function createBunCompileArgs(
	entryPath: string,
	outfilePath: string,
	minify: boolean,
	target: string,
	envFiles: readonly string[] = [],
): string[] {
	return [
		"build",
		"--compile",
		// A standalone otherwise runs the bunfig.toml of whatever directory it is
		// started in, so an unresolvable consumer `preload` would kill it before
		// user code. `.env` autoloading is intentionally left on.
		"--no-compile-autoload-bunfig",
		...toBunEnvFileArgs(envFiles),
		"--env=PUBLIC_*",
		"--define",
		CRUST_BUILD_DEFINE_ARG,
		"--outfile",
		outfilePath,
		...(minify ? ["--minify"] : []),
		"--target",
		target,
		entryPath,
	];
}

function createDenoCompileArgs(
	entryPath: string,
	outfilePath: string,
	target: DenoTarget,
): string[] {
	// No --env-file: `deno compile` embeds EVERY variable from the file into the
	// binary (verified empirically on Deno 2.9 — secrets included), with no
	// equivalent of bun's --env=PUBLIC_* filter. The build command rejects
	// --env-file for the deno runtime instead of leaking secrets.
	return [
		"compile",
		// -A: Crust core reads process.env before dispatch, so a sandboxed binary
		// crashes with NotCapable on startup. Full grants also match Bun compile,
		// which has no sandbox. A permission passthrough flag can narrow this later.
		"-A",
		"--output",
		outfilePath,
		"--target",
		target,
		entryPath,
	];
}

async function runBuildProcess(
	runner: BuildRunner,
	args: readonly string[],
	outfilePath: string,
	cwd: string,
): Promise<void> {
	const { exitCode, stdout, stderr } = await runProcess(runner.command, args, {
		env: runner.env,
		cwd,
		stdio: "collect",
	});

	if (exitCode !== 0) {
		const output = [stderr.trim(), stdout.trim()].filter(Boolean).join("\n");
		throw new Error(`Build failed for ${outfilePath}${output ? `:\n${output}` : ""}`);
	}
}

/** Bundle a Node runtime package entry: ESM for Node behind `#!/usr/bin/env node`. */
export async function execNodeBuild(
	entryPath: string,
	outfilePath: string,
	minify: boolean,
	envFiles: readonly string[],
	cwd: string,
	bunPlugins: readonly string[] = [],
	runner: BuildRunner = resolveBunBuildRunner(),
): Promise<void> {
	await execScriptBuild("node", entryPath, outfilePath, minify, envFiles, cwd, bunPlugins, runner);
}

/**
 * Bundle a Bun runtime package entry: Bun-targeted ESM behind
 * `#!/usr/bin/env bun`, so the installed bin launches with Bun rather than Node.
 */
export async function execBunPackageBuild(
	entryPath: string,
	outfilePath: string,
	minify: boolean,
	envFiles: readonly string[],
	cwd: string,
	bunPlugins: readonly string[] = [],
	runner: BuildRunner = resolveBunBuildRunner(),
): Promise<void> {
	await execScriptBuild("bun", entryPath, outfilePath, minify, envFiles, cwd, bunPlugins, runner);
}

async function execScriptBuild(
	target: "bun" | "node",
	entryPath: string,
	outfilePath: string,
	minify: boolean,
	envFiles: readonly string[],
	cwd: string,
	bunPlugins: readonly string[],
	runner: BuildRunner,
): Promise<void> {
	if (bunPlugins.length > 0) {
		await runBunPluginDriver(
			{
				entrypoints: [entryPath],
				minify,
				env: "PUBLIC_*",
				target,
				format: "esm",
			},
			outfilePath,
			bunPlugins,
			envFiles,
			cwd,
			runner,
		);
	} else {
		await runBuildProcess(
			runner,
			[
				"build",
				...toBunEnvFileArgs(envFiles),
				"--env=PUBLIC_*",
				"--define",
				CRUST_BUILD_DEFINE_ARG,
				"--target",
				target,
				"--format",
				"esm",
				"--outfile",
				outfilePath,
				...(minify ? ["--minify"] : []),
				entryPath,
			],
			outfilePath,
			cwd,
		);
	}

	const output = await readFile(outfilePath, "utf8");
	const shebang = `#!/usr/bin/env ${target}\n`;
	await writeFile(outfilePath, shebang + output.replace(/^#![^\n]*(?:\n|$)/, ""));
	if (process.platform !== "win32") await chmod(outfilePath, 0o755);
}

export async function execDenoBuild(
	entryPath: string,
	outfilePath: string,
	target: DenoTarget,
	cwd: string,
	runner: BuildRunner = resolveDenoBuildRunner(),
): Promise<void> {
	await runBuildProcess(
		runner,
		createDenoCompileArgs(entryPath, outfilePath, target),
		outfilePath,
		cwd,
	);
}

/**
 * Bundle a Deno runtime package entry with native `deno bundle`, which resolves
 * dependencies through the project's own Deno setup (deno.json imports,
 * package.json with its installed node_modules) and inlines them into one file.
 *
 * Bundle the declared command directly so Deno preserves its `import.meta.main`
 * semantics without making dependencies main. Prepend the packaged-build marker
 * (`PACKAGED_BUILD_KEY`) to the bundled code so it runs before the inlined
 * application graph. The output has no shebang or permission flags: consumers
 * choose grants with `deno run` / `deno install`.
 * No env files or plugins: `deno bundle` has no PUBLIC_* filter or Bun plugins.
 */
export async function execDenoPackageBuild(
	entryPath: string,
	outfilePath: string,
	cwd: string,
	runner: BuildRunner = resolveDenoBuildRunner(),
): Promise<void> {
	await runBuildProcess(
		runner,
		[
			"bundle",
			"--platform=deno",
			"--packages=bundle",
			"--output",
			outfilePath,
			resolve(cwd, entryPath),
		],
		outfilePath,
		cwd,
	);
	const output = await readFile(outfilePath, "utf8");
	await writeFile(
		outfilePath,
		`globalThis[Symbol.for(${JSON.stringify(PACKAGED_BUILD_KEY)})] = true;\n` +
			output.replace(/^#![^\n]*(?:\n|$)/, ""),
	);
}
