import type { DistributionTarget } from "./distribute.ts";

/** Platform binary filename: `<command>-<target>`, `.exe` on Windows. */
export function binaryFilename(command: string, target: DistributionTarget): string {
	return `${command}-${target.target}${target.os === "win32" ? ".exe" : ""}`;
}

export function generateLauncher(command: string, targets: readonly DistributionTarget[]): string {
	const targetMap = Object.fromEntries(
		targets.map((target) => [
			target.platformKey,
			{
				packagePathSegment: target.packagePathSegment,
				packageName: target.packageName,
				targetAlias: target.targetAlias,
				binaryFilename: binaryFilename(command, target),
			},
		]),
	);
	const supportedPlatforms = targets.map((target) => target.targetAlias).join(", ");

	// The command name is validated by the build planner and embedded as a JSON
	// string literal, never spliced into code.
	return `#!/usr/bin/env node
// Auto-generated by crust build -- do not edit
import { spawn } from "node:child_process";
import { chmodSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const NAME = ${JSON.stringify(command)};
const PLATFORMS = ${JSON.stringify(targetMap, null, "\t")};
const dir = dirname(fileURLToPath(import.meta.url));

// Same check as Bun's own npm installer: glibc reports its version, musl does not.
function isMusl() {
	try {
		const report = process.report?.getReport();
		if (report?.header) return report.header.glibcVersionRuntime === undefined;
	} catch {}
	return existsSync("/etc/alpine-release");
}

const platformKey =
	\`\${process.platform}-\${process.arch}\` + (process.platform === "linux" && isMusl() ? "-musl" : "");
const target = PLATFORMS[platformKey];

if (!target) {
\tconsole.error("[" + NAME + "] Unsupported platform: " + platformKey);
\tconsole.error("[" + NAME + "] Supported platforms: ${supportedPlatforms}");
\tprocess.exit(1);
}

const candidates = [
\t// Hoisted install: the platform package beside this one in node_modules.
\tresolve(dir, "..", "..", target.packagePathSegment, "bin", target.binaryFilename),
\t// Nested install: the platform package under this package's node_modules.
\tresolve(dir, "..", "node_modules", target.packageName, "bin", target.binaryFilename),
\t// In place: the .crust/ tree crust build staged, before any install.
\tresolve(dir, "..", "..", target.targetAlias, "bin", target.binaryFilename),
];
const binPath = candidates.find((candidate) => existsSync(candidate));

if (!binPath) {
\tconsole.error("[" + NAME + "] Missing platform package for " + platformKey);
\tconsole.error("[" + NAME + "] Tried:");
\tfor (const candidate of candidates) console.error("  " + candidate);
\tconsole.error(
\t\t"[" + NAME + "] Reinstall dependencies on this platform and ensure optional dependencies are enabled.",
\t);
\tprocess.exit(1);
}

if (process.platform !== "win32") {
\ttry {
\t\tchmodSync(binPath, 0o755);
\t} catch {
\t\t// Ignore permission adjustment failures and let spawn surface real errors.
\t}
}

const child = spawn(binPath, process.argv.slice(2), {
\tstdio: "inherit",
});

child.on("error", (error) => {
\tconsole.error("[" + NAME + "] Failed to launch binary: " + error.message);
\tprocess.exit(1);
});

child.on("exit", (code, signal) => {
\tif (signal) {
\t\ttry {
\t\t\tprocess.kill(process.pid, signal);
\t\t} catch {
\t\t\tprocess.exit(1);
\t\t}
\t\treturn;
\t}

\tprocess.exit(code ?? 0);
});
`;
}
