import { existsSync, readFileSync, realpathSync } from "node:fs";
import { copyFile, mkdtemp, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { isJsonObject, type JsonObject, type JsonValue } from "@crustjs/utils/json";
import { type RunProcessResult, runProcess } from "@crustjs/utils/process";
import satisfies from "semver/functions/satisfies.js";
import validVersion from "semver/functions/valid.js";

import crustPackage from "../package.json" with { type: "json" };
import { type BundleSettings, execScriptBuild, runBuildProcess } from "./bundle.ts";
import {
	assertCompilerSatisfiesEngines,
	type BuildCompiler,
	type BuildRunner,
	isVersionRange,
	processOutput,
	readCompilerVersion,
	resolveNodeBuildRunner,
} from "./compilers.ts";
import { NODE_TARGETS, type NodeTarget } from "./targets.ts";

/**
 * Crust's own optional dependencies that build Node standalone binaries.
 * Crust's staged root and platform packages declare them
 * (scripts/stage-node-exe-dependencies.ts) so an installed crust resolves them
 * next to itself; an install that skipped them only affects Node binaries.
 */
export const NODE_EXE_BACKEND_PACKAGES = ["tsdown", "@tsdown/exe"] as const;

/** Crust's installed tsdown, as the selected Node resolves and loads it. */
export type NodeExeBackend = {
	/** tsdown's package.json, resolved from Crust's own installation. */
	packageJsonPath: string;
	version: string;
	/** tsdown's package `engines.node`. */
	engines: string;
	/** Oldest Node tsdown's executable builder accepts (Node SEA with an ESM entry). */
	seaMinVersion: string;
};

/** The selected external Node together with the backend it builds binaries with. */
export type NodeBinaryCompiler = BuildCompiler & { runtime: "node"; backend: NodeExeBackend };

/**
 * A file of Crust's own installation that the backend is resolved from, never
 * the project or PATH. A compiled crust serves its modules from Bun's virtual
 * filesystem (`/$bunfs/`, `B:/~BUN/` on Windows), so there it is the
 * executable, inside its platform package.
 */
export function crustInstallPath(moduleUrl = import.meta.url, execPath = process.execPath): string {
	return /^file:\/\/\/(?:\$bunfs|[A-Za-z]:\/~BUN)\//.test(moduleUrl)
		? execPath
		: fileURLToPath(moduleUrl);
}

/**
 * `<dir>/node_modules/<name>/package.json` for the nearest `dir` at or above
 * `from`: Node's node_modules lookup without its NODE_PATH and global-folder
 * fallbacks, so only an installation next to `from` can supply the package.
 * Package managers hoist crust's backend into the project's node_modules, so
 * the found package may be the project's own: callers check its version.
 */
function findInstalledPackageJson(from: string, name: string): string | null {
	for (let dir = from; ; dir = dirname(dir)) {
		const candidate = join(dir, "node_modules", name, "package.json");
		if (existsSync(candidate)) return candidate;
		if (dirname(dir) === dir) return null;
	}
}

function isVersionedPackageJson(value: JsonValue): value is JsonObject & { version: string } {
	return isJsonObject(value) && typeof value.version === "string";
}

function isTsdownPackageJson(
	value: JsonValue,
): value is JsonObject & { version: string; engines: JsonObject & { node: string } } {
	return (
		isVersionedPackageJson(value) &&
		value.engines !== undefined &&
		isJsonObject(value.engines) &&
		value.engines.node !== undefined &&
		isVersionRange(value.engines.node)
	);
}

// Loads tsdown's executable-builder minimum under the selected Node, the way
// the build loads tsdown: as a self-reference from its package.json.
function createNodeExeProbeScript(tsdownPackageJson: string): string {
	return `// Generated by crust build to read tsdown's executable minimum; deleted when it exits.
import { createRequire } from "node:module";
import { pathToFileURL } from "node:url";

const internal = createRequire(${JSON.stringify(tsdownPackageJson)}).resolve("tsdown/internal");
console.log((await import(pathToFileURL(internal).href)).NODE_SEA_MIN_VERSION);
`;
}

const NODE_TOOLCHAIN_GUIDANCE =
	"  Binaries embed the selected node's version; crust does not install or upgrade it.\n  Put a supported node first on PATH (e.g. with your version manager).";

/**
 * Checks the selected Node against the installed backend's two separate
 * requirements: tsdown's package `engines.node` and its executable builder's
 * minimum (skipped while unknown). Both come from the installed tsdown, not
 * from this file.
 */
export function assertNodeExeBackendSupports(
	compiler: BuildCompiler,
	backend: Pick<NodeExeBackend, "version" | "engines"> & { seaMinVersion?: string },
): void {
	const selected = `Node ${compiler.version} (${compiler.runner.command})`;
	if (!satisfies(compiler.version, backend.engines)) {
		throw new Error(
			`${selected} is not supported by tsdown ${backend.version}, which builds node standalone binaries: its package requires Node "${backend.engines}".\n${NODE_TOOLCHAIN_GUIDANCE}`,
		);
	}
	if (
		backend.seaMinVersion !== undefined &&
		!satisfies(compiler.version, `>=${backend.seaMinVersion}`)
	) {
		throw new Error(
			`${selected} cannot build standalone executables: tsdown ${backend.version}'s executable builder requires Node ${backend.seaMinVersion} or later.\n${NODE_TOOLCHAIN_GUIDANCE}`,
		);
	}
}

/**
 * Finds Crust's installed tsdown and @tsdown/exe from `installPath`, at the
 * versions its package.json `optionalDependencies` pin, and validates the
 * selected Node against tsdown's requirements, loading the executable
 * builder's minimum under that Node. `cwd` is the project
 * directory, as for every other compiler step.
 */
export async function resolveNodeExeBackend(
	compiler: BuildCompiler,
	cwd: string,
	installPath: string = crustInstallPath(),
): Promise<NodeExeBackend> {
	const reinstall =
		`  @crustjs/crust ships ${NODE_EXE_BACKEND_PACKAGES.join(" and ")} as optional dependencies, which package managers skip when optional dependencies are disabled or the installing node does not satisfy tsdown's engines.\n` +
		"  Reinstall @crustjs/crust with optional dependencies enabled under a node that can build Node binaries (e.g. the one on PATH here).";
	const packageJsonPath = findInstalledPackageJson(dirname(installPath), "tsdown");
	if (packageJsonPath === null) {
		throw new Error(
			`tsdown, which builds node standalone binaries, is not installed with crust (${installPath}).\n${reinstall}`,
		);
	}
	// tsdown imports @tsdown/exe from its real location for executable targets.
	const exePackageJsonPath = findInstalledPackageJson(
		dirname(realpathSync(packageJsonPath)),
		"@tsdown/exe",
	);
	if (exePackageJsonPath === null) {
		throw new Error(
			`@tsdown/exe is not installed beside crust's tsdown (${packageJsonPath}).\n${reinstall}`,
		);
	}
	const readPackage = (path: string): JsonValue => JSON.parse(readFileSync(path, "utf8"));
	const tsdownPackage = readPackage(packageJsonPath);
	// Before running any of it: when crust's copy was skipped, the lookup can reach the project's own.
	for (const [name, path] of [
		["tsdown", packageJsonPath],
		["@tsdown/exe", exePackageJsonPath],
	] as const) {
		// Read @tsdown/exe only after tsdown passes, so a mismatched tsdown reports the guidance first.
		const installed = name === "tsdown" ? tsdownPackage : readPackage(path);
		const version = isVersionedPackageJson(installed) ? installed.version : "without a version";
		const pinned = crustPackage.optionalDependencies[name];
		if (!satisfies(version, pinned)) {
			throw new Error(
				`${name} ${version} (${path}) is not the ${name} ${pinned} that crust builds node standalone binaries with.\n${reinstall}`,
			);
		}
	}
	if (!isTsdownPackageJson(tsdownPackage)) {
		throw new Error(`Unexpected tsdown package metadata in ${packageJsonPath}.\n${reinstall}`);
	}
	const backend = {
		packageJsonPath,
		version: tsdownPackage.version,
		engines: tsdownPackage.engines.node,
	};
	assertNodeExeBackendSupports(compiler, backend);

	const probe = await runGeneratedScript(
		compiler.runner,
		"probe",
		createNodeExeProbeScript(packageJsonPath),
		cwd,
	);
	const seaMinVersion = probe.exitCode === 0 ? validVersion(probe.stdout.trim()) : null;
	if (seaMinVersion === null) {
		const output = processOutput(probe);
		throw new Error(
			`tsdown ${backend.version}'s executable builder could not be loaded with ${compiler.runner.command} (exit ${probe.exitCode}).\n${reinstall}${output ? `\n${output}` : ""}`,
		);
	}
	const resolved = { ...backend, seaMinVersion };
	assertNodeExeBackendSupports(compiler, resolved);
	return resolved;
}

/**
 * Select the Node binary compiler once for a build: the external `node`, its
 * version read in the project directory `cwd`, validated against the
 * project's `engines.node` and then the installed tsdown's requirements.
 * Pass it to {@link execNodeBinaryBuild} for every command and target.
 */
export async function resolveNodeBinaryCompiler(
	userPackageJson: JsonObject,
	cwd: string,
): Promise<NodeBinaryCompiler> {
	const runner = resolveNodeBuildRunner();
	const compiler = {
		runtime: "node" as const,
		runner,
		version: await readCompilerVersion("node", runner, cwd),
	};
	assertCompilerSatisfiesEngines(compiler, userPackageJson);
	return { ...compiler, backend: await resolveNodeExeBackend(compiler, cwd) };
}

/** tsdown's `ExeTarget` (`@tsdown/exe`): Node's release platform and arch, and the exact embedded version. */
export type NodeExeTarget = {
	platform: "linux" | "darwin" | "win";
	arch: "x64" | "arm64";
	nodeVersion: string;
};

/** tsdown's executable target for a Node target, embedding exactly `nodeVersion`. */
export function nodeExeTarget(target: NodeTarget, nodeVersion: string): NodeExeTarget {
	const { os, cpu } = NODE_TARGETS.info[target];
	return { platform: os === "win32" ? "win" : os, arch: cpu, nodeVersion };
}

type NodeExeBuildScriptOptions = {
	tsdownPackageJson: string;
	cwd: string;
	entry: string;
	bundleDir: string;
	exeDir: string;
	minify: boolean;
	target: NodeExeTarget;
};

/**
 * Script the selected Node runs to turn one Bun bundle into one target's
 * executable with tsdown's programmatic `build`. Every value is embedded via
 * JSON.stringify.
 */
function createNodeExeBuildScript(options: NodeExeBuildScriptOptions): string {
	return `// Generated by crust build for a Node standalone binary; deleted when the build finishes.
import { createRequire } from "node:module";
import { pathToFileURL } from "node:url";

const options = ${JSON.stringify(options)};
const { build } = await import(pathToFileURL(createRequire(options.tsdownPackageJson).resolve("tsdown")).href);
await build({
	config: false,
	cwd: options.cwd,
	entry: { app: options.entry },
	outDir: options.bundleDir,
	format: "esm",
	platform: "node",
	dts: false,
	// Rolldown reprints the Bun bundle, so it minifies again.
	minify: options.minify,
	logLevel: "warn",
	report: false,
	// Bun already inlined the PUBLIC_* constants; inline nothing from this environment.
	envPrefix: [],
	// Bun leaves only Node built-ins as imports; fail on anything else, which
	// an executable shipping no node_modules could not resolve.
	deps: { alwaysBundle: () => true, onlyBundle: false, onlyImport: [] },
	exe: { outDir: options.exeDir, fileName: "app", targets: [options.target] },
});
`;
}

/**
 * Build a single entry file into a Node standalone executable: Bun first
 * bundles it for Node exactly as a Node runtime package ({@link execScriptBuild}:
 * `PUBLIC_*` constants from `envFiles` and the environment, each module's own
 * `import.meta.main` and `require.main === module`, CommonJS and ESM inputs),
 * then tsdown's executable builder (Node SEA), run by the selected external
 * Node, turns that bundle into an executable embedding exactly its version
 * for `target`. tsdown takes a single entry per executable, so callers build
 * every command separately. Matching official Node binaries for targets are
 * downloaded, checksum-verified, and cached by @tsdown/exe. Builds for darwin
 * are only code-signed on a macOS host.
 *
 * @param compiler - The selected Node compiler (`resolveNodeBinaryCompiler`)
 * @param bunRunner - The Bun that bundles (`resolveBunBuildRunner`)
 * @param onWarning - Receives the backend's warnings (such as a skipped code
 *   signature) after a successful build
 * @throws {Error} If the build fails
 */
export async function execNodeBinaryBuild(
	entryPath: string,
	outfilePath: string,
	target: NodeTarget,
	settings: Omit<BundleSettings, "bunPlugins">,
	compiler: NodeBinaryCompiler,
	bunRunner: BuildRunner,
	onWarning: (message: string) => void = () => {},
): Promise<void> {
	const { cwd, minify } = settings;
	const workDir = await mkdtemp(join(tmpdir(), "crust-node-exe-"));
	try {
		const scriptPath = join(workDir, "build.mjs");
		const bunBundle = join(workDir, "app.mjs");
		const exeDir = join(workDir, "exe");
		// ponytail: rebundled per target; bundle once per command if many targets get slow.
		await execScriptBuild(
			"node",
			resolve(cwd, entryPath),
			bunBundle,
			{ ...settings, bunPlugins: [] },
			bunRunner,
		);
		await writeFile(
			scriptPath,
			createNodeExeBuildScript({
				tsdownPackageJson: compiler.backend.packageJsonPath,
				cwd,
				entry: bunBundle,
				bundleDir: join(workDir, "bundle"),
				exeDir,
				minify,
				target: nodeExeTarget(target, compiler.version),
			}),
		);
		const output = await runBuildProcess(compiler.runner, [scriptPath], outfilePath, cwd);
		const produced = await readdir(exeDir);
		if (produced.length !== 1) {
			throw new Error(
				`Build failed for ${outfilePath}: expected one executable from tsdown, found ${JSON.stringify(produced)}.`,
			);
		}
		await copyFile(join(exeDir, produced[0]!), outfilePath);
		if (output) onWarning(output);
	} finally {
		await rm(workDir, { recursive: true, force: true, maxRetries: 3, retryDelay: 100 });
	}
}

// Calls @tsdown/exe's `resolveNodeBinary` for each target exactly as tsdown's
// executable builder does (no download options), loading @tsdown/exe from
// tsdown's real location, where tsdown imports it from.
function createNodeExeProvisionScript(
	tsdownPackageJson: string,
	targets: ReadonlyArray<{ name: NodeTarget; target: NodeExeTarget }>,
): string {
	return `// Generated by crust build to provision Node binaries for targets; deleted when it exits.
import { realpathSync } from "node:fs";
import { createRequire } from "node:module";
import { pathToFileURL } from "node:url";

const exe = createRequire(realpathSync(${JSON.stringify(tsdownPackageJson)})).resolve("@tsdown/exe");
const { resolveNodeBinary } = await import(pathToFileURL(exe).href);
for (const { name, target } of ${JSON.stringify(targets)}) {
	try {
		await resolveNodeBinary(target, {});
	} catch (error) {
		console.error(name + ": " + error.message + (error.cause?.message ? "\\n" + error.cause.message : ""));
		process.exit(1);
	}
}
`;
}

/**
 * Provisions the Node binary every target embeds before anything is staged,
 * with the selected Node and the call tsdown's executable builder makes per
 * target (@tsdown/exe's `resolveNodeBinary`): an uncached official archive of
 * exactly `compiler.version` is downloaded, checksum-verified, unpacked with
 * the tool that target's archive needs on this host, and cached, where
 * {@link execNodeBinaryBuild} then finds it. A missing unpacking tool, a failed
 * download, or a checksum mismatch therefore fails here, before `.crust/` is
 * replaced; cached targets need nothing.
 *
 * @throws {Error} If a target cannot be provisioned
 */
export async function provisionNodeExeTargets(
	targets: readonly NodeTarget[],
	cwd: string,
	compiler: NodeBinaryCompiler,
): Promise<void> {
	const provision = await runGeneratedScript(
		compiler.runner,
		"provision",
		createNodeExeProvisionScript(
			compiler.backend.packageJsonPath,
			targets.map((name) => ({ name, target: nodeExeTarget(name, compiler.version) })),
		),
		cwd,
	);
	if (provision.exitCode !== 0) {
		const output = processOutput(provision);
		throw new Error(
			`Could not provision the Node ${compiler.version} binary that node standalone binaries embed${output ? `:\n${output}` : "."}\n` +
				"  tsdown downloads each target's official Node archive once and unpacks it with tar (GNU tar also needs xz for linux targets), or unzip for win targets on non-Windows hosts.\n" +
				"  Install the missing tool, or build only targets this machine can provision (--target).",
		);
	}
}

/** Runs a generated `<name>.mjs` with `runner` from a temporary directory that is removed afterwards. */
async function runGeneratedScript(
	runner: BuildRunner,
	name: string,
	source: string,
	cwd: string,
): Promise<RunProcessResult> {
	const workDir = await mkdtemp(join(tmpdir(), `crust-node-exe-${name}-`));
	try {
		const scriptPath = join(workDir, `${name}.mjs`);
		await writeFile(scriptPath, source);
		return await runProcess(runner.command, [scriptPath], {
			env: runner.env,
			cwd,
			stdio: "collect",
		});
	} finally {
		await rm(workDir, { recursive: true, force: true });
	}
}
