import type { CommandSnapshot } from "@crustjs/core";

/** Metadata used to render a generated skill. */
export interface SkillMeta {
	name: string;
	description: string;
	version: string;
}

/** Supported agent targets for skill installation. */
export type AgentTarget =
	| "amp"
	| "adal"
	| "antigravity"
	| "augment"
	| "claude-code"
	| "cline"
	| "codebuddy"
	| "codex"
	| "command-code"
	| "continue"
	| "cortex"
	| "crush"
	| "cursor"
	| "droid"
	| "gemini-cli"
	| "github-copilot"
	| "goose"
	| "iflow-cli"
	| "junie"
	| "kilo"
	| "kimi-cli"
	| "kiro-cli"
	| "kode"
	| "mcpjam"
	| "mistral-vibe"
	| "mux"
	| "neovate"
	| "opencode"
	| "openclaw"
	| "openhands"
	| "pi"
	| "pochi"
	| "qoder"
	| "qwen-code"
	| "replit"
	| "roo"
	| "trae"
	| "trae-cn"
	| "windsurf"
	| "zencoder";

export type AgentClass = "universal" | "additional";
export type Scope = "global" | "project";

// ────────────────────────────────────────────────────────────────────────────
// Command manifest — canonical intermediate representation
// ────────────────────────────────────────────────────────────────────────────

/**
 * Describes a single positional argument in the canonical manifest.
 *
 * Normalized from `DocumentationArg` in `@crustjs/core/tooling` to a flat, serializable shape.
 */
export interface ManifestArg {
	name: string;
	type: "string" | "number" | "boolean";
	description?: string;
	required: boolean;
	variadic: boolean;
	default?: string;
}

export interface ManifestFlag {
	name: string;
	/** All accepted CLI spellings in documentation order — the sole source for rendered flag labels */
	spellings: readonly string[];
	type: "string" | "number" | "boolean";
	description?: string;
	required: boolean;
	multiple: boolean;
	short?: string;
	aliases: string[];
	default?: string;
}

/**
 * Canonical representation of a single command node in the manifest tree.
 *
 * Generated by introspecting Crust builder metadata. The manifest is
 * the intermediate representation between raw command definitions and
 * rendered markdown output.
 *
 * @example
 * ```ts
 * // A leaf command: git remote add
 * const node: ManifestNode = {
 *   name: "add",
 *   path: ["git", "remote", "add"],
 *   description: "Add a new remote",
 *   runnable: true,
 *   usage: "git remote add <name>",
 *   args: [{ name: "name", type: "string", required: true, variadic: false }],
 *   flags: [{ name: "fetch", spellings: ["--fetch", "--no-fetch"], type: "boolean", required: false, multiple: false, aliases: [] }],
 *   children: [],
 * };
 * ```
 */
export interface ManifestNode {
	name: string;
	path: string[];
	description?: string;
	usage: string;
	/** Plain-text command sections rendered into the command's markdown file. */
	sections?: CommandSnapshot["meta"]["sections"];
	runnable: boolean;
	args: ManifestArg[];
	flags: ManifestFlag[];
	children: ManifestNode[];
}

export interface RenderedFile {
	path: string;
	content: string | Uint8Array;
}

/** Options for linking one packaged skill source into agent directories. */
export interface InstallSkillOptions {
	/** Package directory `skills/<name>` containing the skill's SKILL.md. */
	sourceDir: string | URL;
	/** Agent targets. Omit to use universal plus PATH-detected agents. */
	agents?: AgentTarget[];
	/** Agent-directory scope. @default "global" */
	scope?: Scope;
	/** Allow replacing a directory that is not owned by this skill. @default false */
	force?: boolean;
}

export type InstallStatus = "installed" | "repaired" | "up-to-date";
export type UninstallStatus = "removed" | "not-found";

export interface AgentResult {
	agent: AgentTarget;
	outputDir: string;
	status: InstallStatus;
}

export interface InstallSkillResult {
	agents: AgentResult[];
}

export interface UninstallSkillOptions {
	name: string;
	agents?: AgentTarget[];
	scope?: Scope;
}

export interface UninstallSkillResult {
	agents: Array<{
		agent: AgentTarget;
		outputDir: string;
		status: UninstallStatus;
	}>;
}

export interface SkillStatusOptions {
	name: string;
	/** Expected source used to identify stale-target links. */
	sourceDir: string | URL;
	agents?: AgentTarget[];
	scope?: Scope;
}

export type SkillLinkStatus = "linked" | "dangling" | "conflict" | "absent";

export interface SkillStatusResult {
	agents: Array<{
		agent: AgentTarget;
		outputDir: string;
		status: SkillLinkStatus;
	}>;
}

/** Options for the skills extension. */
export interface SkillOptions {
	/** Read-only directory produced by writeSkills(). */
	source: string | URL;
	/** Default agent-directory scope. */
	defaultScope?: Scope;
	/** Repair stale or dangling owned links before commands run. @default true */
	autoUpdate?: boolean;
	/** Name of the interactive management command. @default "skill" */
	command?: string;
}
