// ────────────────────────────────────────────────────────────────────────────
// @crustjs/skills — Public types for agent skill generation
// ────────────────────────────────────────────────────────────────────────────

import type { AnyCommand } from "@crustjs/core";

// ────────────────────────────────────────────────────────────────────────────
// Skill metadata — describes the generated skill bundle
// ────────────────────────────────────────────────────────────────────────────

/**
 * Metadata for the generated skill bundle.
 *
 * This information populates the `SKILL.md` frontmatter and distribution
 * metadata files (`crust.json`).
 *
 * @example
 * ```ts
 * const meta: SkillMeta = {
 *   name: "my-cli",
 *   description: "CLI tool for managing widgets",
 *   version: "1.0.0",
 * };
 * // generateSkill() will output to `use-my-cli/` with name "use-my-cli"
 * ```
 */
export interface SkillMeta {
	/**
	 * Skill name — the user-facing CLI name (e.g. `"my-cli"`).
	 *
	 * `generateSkill()`, `uninstallSkill()`, and `skillStatus()` automatically
	 * prefix `use-` to this name for output directory paths, SKILL.md frontmatter,
	 * and crust.json metadata. For example, `name: "my-cli"` produces output
	 * under `use-my-cli/`.
	 *
	 * The resolved name (with `use-` prefix) must conform to the Agent Skills
	 * spec: 1–64 lowercase alphanumeric characters and hyphens, no leading/
	 * trailing/consecutive hyphens.
	 */
	name: string;
	/** Human-readable description of what the CLI does */
	description: string;
	/** Version string for the generated skill bundle */
	version: string;
	/**
	 * License name or reference to a bundled license file.
	 *
	 * Emitted in SKILL.md YAML frontmatter as `license:`.
	 */
	license?: string;
	/**
	 * Environment requirements or compatibility notes (max 500 chars per spec).
	 *
	 * Indicates intended product, required system packages, network access, etc.
	 * Emitted in SKILL.md YAML frontmatter as `compatibility:`.
	 *
	 * @example "Requires deploy-cli installed on PATH"
	 */
	compatibility?: string;
	/**
	 * When `true`, prevents agents from automatically loading this skill.
	 * Users must invoke it manually with `/skill-name`.
	 *
	 * Emitted in SKILL.md YAML frontmatter as `disable-model-invocation: true`.
	 * @default false
	 */
	disableModelInvocation?: boolean;
	/**
	 * Space-delimited list of pre-approved tools the skill may use.
	 *
	 * For CLI skills, setting this to `Bash(<cli-name> *)` allows agents to
	 * execute the CLI without per-use permission prompts.
	 *
	 * Emitted in SKILL.md YAML frontmatter as `allowed-tools:`.
	 *
	 * @example "Bash(my-cli *) Read Grep"
	 */
	allowedTools?: string;
}

// ────────────────────────────────────────────────────────────────────────────
// Agent and scope types
// ────────────────────────────────────────────────────────────────────────────

/** Supported agent targets for skill installation. */
export type AgentTarget = "claude-code" | "opencode";

/** Installation scope — global (home directory) or project (cwd). */
export type Scope = "global" | "project";

// ────────────────────────────────────────────────────────────────────────────
// Command manifest — canonical intermediate representation
// ────────────────────────────────────────────────────────────────────────────

/**
 * Describes a single positional argument in the canonical manifest.
 *
 * Normalized from `ArgDef` in `@crustjs/core` to a flat, serializable shape.
 */
export interface ManifestArg {
	/** Argument name (from `ArgDef.name`) */
	name: string;
	/** Value type: "string", "number", or "boolean" */
	type: "string" | "number" | "boolean";
	/** Human-readable description */
	description?: string;
	/** Whether this argument is required */
	required: boolean;
	/** Whether this argument collects remaining values into an array */
	variadic: boolean;
	/** Default value (serialized as string for deterministic output) */
	default?: string;
}

/**
 * Describes a single named flag in the canonical manifest.
 *
 * Normalized from `FlagDef` in `@crustjs/core` to a flat, serializable shape.
 */
export interface ManifestFlag {
	/** Flag name (the key from `FlagsDef`) */
	name: string;
	/** Value type: "string", "number", or "boolean" */
	type: "string" | "number" | "boolean";
	/** Human-readable description */
	description?: string;
	/** Whether this flag is required */
	required: boolean;
	/** Whether this flag accepts multiple values */
	multiple: boolean;
	/** Short alias(es) */
	aliases: string[];
	/** Default value (serialized as string for deterministic output) */
	default?: string;
}

/**
 * Canonical representation of a single command node in the manifest tree.
 *
 * Generated by introspecting `defineCommand` metadata. The manifest is
 * the intermediate representation between raw command definitions and
 * rendered markdown output.
 *
 * @example
 * ```ts
 * // A leaf command: git remote add
 * const node: ManifestNode = {
 *   name: "add",
 *   path: ["git", "remote", "add"],
 *   description: "Add a new remote",
 *   runnable: true,
 *   args: [{ name: "name", type: "string", required: true, variadic: false }],
 *   flags: [{ name: "fetch", type: "boolean", required: false, multiple: false, aliases: ["f"] }],
 *   children: [],
 * };
 * ```
 */
export interface ManifestNode {
	/** Command name (final segment of the command path) */
	name: string;
	/** Full command path from root (e.g. `["git", "remote", "add"]`) */
	path: string[];
	/** Human-readable description */
	description?: string;
	/** Custom usage string (overrides auto-generated usage) */
	usage?: string;
	/** Whether this command has a `run` handler (leaf vs group) */
	runnable: boolean;
	/** Positional argument definitions */
	args: ManifestArg[];
	/** Flag definitions */
	flags: ManifestFlag[];
	/** Child command nodes (subcommands) */
	children: ManifestNode[];
}

// ────────────────────────────────────────────────────────────────────────────
// Rendered output — files to write to disk
// ────────────────────────────────────────────────────────────────────────────

/**
 * A single rendered file ready for writing to the output directory.
 *
 * File paths are relative to the skill output directory
 * (e.g. `"SKILL.md"`, `"commands/remote/add.md"`).
 */
export interface RenderedFile {
	/** Relative file path within the skill output directory */
	path: string;
	/** File content (UTF-8 text) */
	content: string;
}

// ────────────────────────────────────────────────────────────────────────────
// Generation options — top-level input for skill generation
// ────────────────────────────────────────────────────────────────────────────

/**
 * Top-level options for generating a skill bundle from a command tree.
 *
 * The `meta.name` value is automatically prefixed with `use-` for all output
 * paths and metadata. For example, `name: "my-cli"` produces skill directories
 * named `use-my-cli/` and sets the manifest/frontmatter name to `"use-my-cli"`.
 *
 * @example
 * ```ts
 * import { generateSkill } from "@crustjs/skills";
 * import { rootCommand } from "./commands.ts";
 *
 * await generateSkill({
 *   command: rootCommand,
 *   meta: {
 *     name: "my-cli", // output: use-my-cli/
 *     description: "CLI tool for managing widgets",
 *     version: "1.0.0",
 *   },
 *   agents: ["claude-code", "opencode"],
 * });
 * ```
 */
export interface GenerateOptions {
	/** Root command to generate the skill from */
	command: AnyCommand;
	/** Skill metadata for the generated bundle */
	meta: SkillMeta;
	/** Agent targets to install skills for */
	agents: AgentTarget[];
	/**
	 * Installation scope — global (home directory) or project (cwd).
	 * @default "global"
	 */
	scope?: Scope;
	/**
	 * When `true`, removes the existing skill directory before writing.
	 * Prevents stale files from previous generations.
	 * @default true
	 */
	clean?: boolean;
	/**
	 * When `true`, overwrite an existing skill directory even if it was not
	 * created by Crust (i.e. has no `crust.json`). Without this flag, a
	 * conflict throws a {@link SkillConflictError}.
	 * @default false
	 */
	force?: boolean;
}

// ────────────────────────────────────────────────────────────────────────────
// Generation result — returned from generateSkill
// ────────────────────────────────────────────────────────────────────────────

/** Status of an individual agent installation. */
export type InstallStatus = "installed" | "updated" | "up-to-date";

/** Status of an individual agent uninstallation. */
export type UninstallStatus = "removed" | "not-found";

/** Per-agent result from a generateSkill call. */
export interface AgentResult {
	/** Which agent this result is for */
	agent: AgentTarget;
	/** Absolute path to the skill output directory for this agent */
	outputDir: string;
	/** List of files that were written (relative paths) */
	files: string[];
	/** What happened during this installation */
	status: InstallStatus;
	/** Previous version string when status is "updated" */
	previousVersion?: string;
}

/**
 * Result returned by `generateSkill` after writing files to disk.
 */
export interface GenerateResult {
	/** Per-agent installation results */
	agents: AgentResult[];
}

// ────────────────────────────────────────────────────────────────────────────
// Uninstall types
// ────────────────────────────────────────────────────────────────────────────

/** Options for removing installed skills. */
export interface UninstallOptions {
	/** Skill name to uninstall */
	name: string;
	/** Agent targets to uninstall from */
	agents: AgentTarget[];
	/**
	 * Installation scope to uninstall from.
	 * @default "global"
	 */
	scope?: Scope;
}

/** Result returned by `uninstallSkill`. */
export interface UninstallResult {
	/** Per-agent uninstall results */
	agents: Array<{
		agent: AgentTarget;
		outputDir: string;
		status: UninstallStatus;
	}>;
}

// ────────────────────────────────────────────────────────────────────────────
// Status types
// ────────────────────────────────────────────────────────────────────────────

/** Options for checking installed skill status. */
export interface StatusOptions {
	/** Skill name to check */
	name: string;
	/** Agent targets to check */
	agents: AgentTarget[];
	/**
	 * Installation scope to check.
	 * @default "global"
	 */
	scope?: Scope;
}

/** Result returned by `skillStatus`. */
export interface StatusResult {
	/** Per-agent status results */
	agents: Array<{
		agent: AgentTarget;
		outputDir: string;
		installed: boolean;
		version?: string;
	}>;
}

// ────────────────────────────────────────────────────────────────────────────
// Plugin option types
// ────────────────────────────────────────────────────────────────────────────

/**
 * Options for the skill plugin.
 *
 * The plugin reads `name` and `description` from the root command's `meta`
 * at setup time, so only `version` is required here.
 *
 * Installed agents are detected automatically by checking for global
 * configuration directories (`~/.claude/` for Claude Code,
 * `~/.config/opencode/` for OpenCode). Only detected agents are managed.
 *
 * **Auto-update** (default): silently updates already-installed skills when a
 * new version is detected. Set `autoInstall: true` to also install skills that
 * are not yet present.
 *
 * **Interactive command**: set `command: true` to register a `skill` subcommand
 * that presents a single multiselect prompt for toggling agent installations.
 */
export interface SkillPluginOptions {
	/** Skill version string — compared against the installed crust.json */
	version: string;
	/**
	 * Installation scope.
	 * @default "global"
	 */
	scope?: Scope;
	/**
	 * Automatically install skills when not yet present.
	 * Set to `true` to install on first CLI invocation without requiring the
	 * interactive skill command.
	 * @default false
	 */
	autoInstall?: boolean;
	/**
	 * Automatically update skills when the installed version is outdated.
	 * @default true
	 */
	autoUpdate?: boolean;
	/**
	 * Register an interactive skill management subcommand on the root command.
	 *
	 * The command presents a single multiselect prompt listing all detected
	 * agents with their current installation status pre-filled. The user
	 * toggles agents on/off and the system reconciles the desired state:
	 * newly selected agents are installed, deselected agents are uninstalled,
	 * and already-correct agents are skipped.
	 *
	 * - `true`: register with default name `"skill"`
	 * - `string`: register with a custom command name
	 * @default false
	 */
	command?: boolean | string;
}
