// ────────────────────────────────────────────────────────────────────────────
// @crustjs/skills — Public types for agent skill generation
// ────────────────────────────────────────────────────────────────────────────

import type { AnyCommand } from "@crustjs/core";

// ────────────────────────────────────────────────────────────────────────────
// Skill metadata — describes the generated skill bundle
// ────────────────────────────────────────────────────────────────────────────

/**
 * Metadata for the generated skill bundle.
 *
 * This information populates the `SKILL.md` frontmatter and distribution
 * metadata files (`manifest.json`, `README.md`).
 *
 * @example
 * ```ts
 * const meta: SkillMeta = {
 *   name: "my-cli",
 *   description: "CLI tool for managing widgets",
 *   version: "1.0.0",
 * };
 * ```
 */
export interface SkillMeta {
	/** Skill name — used as the directory name and in frontmatter */
	name: string;
	/** Human-readable description of what the CLI does */
	description: string;
	/** Optional version string for the generated skill bundle */
	version?: string;
}

// ────────────────────────────────────────────────────────────────────────────
// Command manifest — canonical intermediate representation
// ────────────────────────────────────────────────────────────────────────────

/**
 * Describes a single positional argument in the canonical manifest.
 *
 * Normalized from `ArgDef` in `@crustjs/core` to a flat, serializable shape.
 */
export interface ManifestArg {
	/** Argument name (from `ArgDef.name`) */
	name: string;
	/** Value type: "string", "number", or "boolean" */
	type: "string" | "number" | "boolean";
	/** Human-readable description */
	description?: string;
	/** Whether this argument is required */
	required: boolean;
	/** Whether this argument collects remaining values into an array */
	variadic: boolean;
	/** Default value (serialized as string for deterministic output) */
	default?: string;
}

/**
 * Describes a single named flag in the canonical manifest.
 *
 * Normalized from `FlagDef` in `@crustjs/core` to a flat, serializable shape.
 */
export interface ManifestFlag {
	/** Flag name (the key from `FlagsDef`) */
	name: string;
	/** Value type: "string", "number", or "boolean" */
	type: "string" | "number" | "boolean";
	/** Human-readable description */
	description?: string;
	/** Whether this flag is required */
	required: boolean;
	/** Whether this flag accepts multiple values */
	multiple: boolean;
	/** Short alias(es) */
	aliases: string[];
	/** Default value (serialized as string for deterministic output) */
	default?: string;
}

/**
 * Canonical representation of a single command node in the manifest tree.
 *
 * Generated by introspecting `defineCommand` metadata. The manifest is
 * the intermediate representation between raw command definitions and
 * rendered markdown output.
 *
 * @example
 * ```ts
 * // A leaf command: git remote add
 * const node: ManifestNode = {
 *   name: "add",
 *   path: ["git", "remote", "add"],
 *   description: "Add a new remote",
 *   runnable: true,
 *   args: [{ name: "name", type: "string", required: true, variadic: false }],
 *   flags: [{ name: "fetch", type: "boolean", required: false, multiple: false, aliases: ["f"] }],
 *   children: [],
 * };
 * ```
 */
export interface ManifestNode {
	/** Command name (final segment of the command path) */
	name: string;
	/** Full command path from root (e.g. `["git", "remote", "add"]`) */
	path: string[];
	/** Human-readable description */
	description?: string;
	/** Custom usage string (overrides auto-generated usage) */
	usage?: string;
	/** Whether this command has a `run` handler (leaf vs group) */
	runnable: boolean;
	/** Positional argument definitions */
	args: ManifestArg[];
	/** Flag definitions */
	flags: ManifestFlag[];
	/** Child command nodes (subcommands) */
	children: ManifestNode[];
}

// ────────────────────────────────────────────────────────────────────────────
// Rendered output — files to write to disk
// ────────────────────────────────────────────────────────────────────────────

/**
 * A single rendered file ready for writing to the output directory.
 *
 * File paths are relative to the skill output directory
 * (e.g. `"SKILL.md"`, `"commands/remote/add.md"`).
 */
export interface RenderedFile {
	/** Relative file path within the skill output directory */
	path: string;
	/** File content (UTF-8 text) */
	content: string;
}

// ────────────────────────────────────────────────────────────────────────────
// Write options — controls output behavior
// ────────────────────────────────────────────────────────────────────────────

/**
 * Options controlling how generated files are written to disk.
 */
export interface WriteOptions {
	/**
	 * Output directory path. Files are written under `<outDir>/skills/<name>/`.
	 *
	 * @default "."
	 */
	outDir?: string;
	/**
	 * When `true`, removes the existing skill directory before writing.
	 * Prevents stale files from previous generations.
	 *
	 * @default true
	 */
	clean?: boolean;
}

// ────────────────────────────────────────────────────────────────────────────
// Generation options — top-level input for skill generation
// ────────────────────────────────────────────────────────────────────────────

/**
 * Top-level options for generating a skill bundle from a command tree.
 *
 * Combines the root command input, skill metadata, and write configuration
 * into a single options object for the `generateSkill` API.
 *
 * @example
 * ```ts
 * import { generateSkill } from "@crustjs/skills";
 * import { rootCommand } from "./commands.ts";
 *
 * await generateSkill({
 *   command: rootCommand,
 *   meta: {
 *     name: "my-cli",
 *     description: "CLI tool for managing widgets",
 *     version: "1.0.0",
 *   },
 *   outDir: "./dist",
 * });
 * ```
 */
export interface GenerateOptions extends WriteOptions {
	/** Root command to generate the skill from */
	command: AnyCommand;
	/** Skill metadata for the generated bundle */
	meta: SkillMeta;
}

// ────────────────────────────────────────────────────────────────────────────
// Generation result — returned from generateSkill
// ────────────────────────────────────────────────────────────────────────────

/**
 * Result returned by `generateSkill` after writing files to disk.
 */
export interface GenerateResult {
	/** Absolute path to the generated skill directory */
	outputDir: string;
	/** List of files that were written (relative paths) */
	files: string[];
}
