// ────────────────────────────────────────────────────────────────────────────
// Version checking — reads and compares installed skill versions
// ────────────────────────────────────────────────────────────────────────────

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { InstallStatus, SkillKind } from "./types.ts";

// ────────────────────────────────────────────────────────────────────────────
// Constants
// ────────────────────────────────────────────────────────────────────────────

/**
 * Filename for the Crust-specific metadata file written into each skill
 * directory. Its presence indicates the skill was generated by Crust.
 */
export const CRUST_MANIFEST = "crust.json";

// ────────────────────────────────────────────────────────────────────────────
// Public API
// ────────────────────────────────────────────────────────────────────────────

/**
 * Manifest record extracted from a skill directory's `crust.json`.
 *
 * Returned by {@link readInstalledManifest}. Contains the fields that drive
 * conflict detection and version comparison in the install pipeline.
 */
export interface InstalledSkillManifest {
	/** Installed version string */
	readonly version: string;
	/**
	 * Origin of the installed bundle.
	 *
	 * Legacy `crust.json` files (written before the `kind` field existed) are
	 * normalized to `"generated"` for backward compatibility. New installs
	 * always emit `kind` explicitly.
	 */
	readonly kind: SkillKind;
}

/**
 * Reads the installed manifest from a skill directory's `crust.json`.
 *
 * Returns the version string and the bundle kind. If `crust.json` exists but
 * has no `kind` field (legacy installs written before TP-003), the kind is
 * defaulted to `"generated"` for backward compatibility.
 *
 * If `kind` is **present** but holds an unrecognized value (e.g. a hand-edit
 * typo like `"bundel"`), the manifest is treated as malformed and `null` is
 * returned. This prevents accidental cross-kind installs from slipping past
 * the conflict guard via a typo.
 *
 * @param dir - Absolute path to the skill directory
 * @returns The installed manifest, or `null` if the file is missing/malformed/lacks a version/has an unrecognized kind
 */
export async function readInstalledManifest(
	dir: string,
): Promise<InstalledSkillManifest | null> {
	try {
		const raw = await readFile(join(dir, CRUST_MANIFEST), "utf-8");
		const parsed: unknown = JSON.parse(raw);

		if (
			typeof parsed !== "object" ||
			parsed === null ||
			!("version" in parsed) ||
			typeof (parsed as Record<string, unknown>).version !== "string"
		) {
			return null;
		}

		const version = (parsed as Record<string, unknown>).version as string;
		const rawKind = (parsed as Record<string, unknown>).kind;

		let kind: SkillKind;
		if (rawKind === undefined) {
			// Backward-compat: legacy crust.json files written before TP-003 lack
			// the `kind` field; treat them as generated.
			kind = "generated";
		} else if (rawKind === "bundle" || rawKind === "generated") {
			kind = rawKind;
		} else {
			// `kind` is present but unrecognized — treat the manifest as malformed
			// so the install pipeline raises a clear conflict instead of silently
			// coercing to `generated`.
			return null;
		}

		return { version, kind };
	} catch {
		return null;
	}
}

/**
 * Reads the installed version from a skill directory's `crust.json`.
 *
 * Thin wrapper around {@link readInstalledManifest} retained for backward
 * compatibility with existing call sites that only need the version string.
 *
 * @param dir - Absolute path to the skill directory
 * @returns The version string if found, or `null` if the file is missing or malformed
 */
export async function readInstalledVersion(
	dir: string,
): Promise<string | null> {
	const manifest = await readInstalledManifest(dir);
	return manifest?.version ?? null;
}

/** Result from {@link checkVersion} containing the status and installed version. */
export interface VersionCheckResult {
	/** Installation status */
	status: InstallStatus;
	/** Previously installed version, or `null` if not found */
	installedVersion: string | null;
}

/**
 * Checks whether a skill directory needs installation or update.
 *
 * @param dir - Absolute path to the skill directory
 * @param newVersion - The version being installed
 * @returns The installation status and the currently installed version (if any)
 */
export async function checkVersion(
	dir: string,
	newVersion: string,
): Promise<VersionCheckResult> {
	const installed = await readInstalledVersion(dir);

	if (installed === null) {
		return { status: "installed", installedVersion: null };
	}

	if (installed !== newVersion) {
		return { status: "updated", installedVersion: installed };
	}

	return { status: "up-to-date", installedVersion: installed };
}
