import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { defineCommand } from "@crustjs/core";
import { bold, cyan, dim, green } from "@crustjs/style";

import {
	type BunTarget,
	execBuild,
	getBinaryFilename,
	resolveBaseName,
	resolveTargets,
	TARGET_INFO,
	buildEntrypoint,
} from "../utils/build-helpers.ts";

/**
 * Resolve the output file path for a single-target build.
 *
 * Priority: --outfile > --name (as ./<outdir>/<name>) > package.json name > entry filename
 *
 * @param outfile - Explicit output file path from --outfile flag
 * @param name - Binary name from --name flag
 * @param entry - Resolved entry file path
 * @param cwd - Current working directory
 * @param outdir - Output directory
 * @returns The resolved output file path
 */
export function resolveOutfile(
	outfile: string | undefined,
	name: string | undefined,
	entry: string,
	cwd: string,
	outdir: string,
): string {
	// Explicit --outfile takes highest priority
	if (outfile) {
		return resolve(cwd, outfile);
	}

	const baseName = resolveBaseName(name, entry, cwd);
	return resolve(cwd, outdir, baseName);
}

// ────────────────────────────────────────────────────────────────────────────
// Shell resolver generator (Unix + Windows)
// ────────────────────────────────────────────────────────────────────────────

/**
 * Generate the shell resolver script content (Unix).
 *
 * The resolver detects the platform via `uname -s` and `uname -m`,
 * maps to the correct prebuilt binary, ensures execute permissions,
 * and execs it with all arguments forwarded.
 *
 * @param baseName - The base binary name
 * @param targets - The list of targets that were built
 * @returns The shell resolver script as a string
 */
export function generateResolver(baseName: string, targets: readonly BunTarget[]): string {
	// Build case entries for only the targets that were built (excluding Windows)
	const caseEntries: string[] = [];
	for (const target of targets) {
		if (target.startsWith("bun-windows")) continue;
		const unameKey = TARGET_INFO[target].unameKey;
		const filename = getBinaryFilename(baseName, target);
		caseEntries.push(`\t${unameKey}) bin="${filename}" ;;`);
	}
	const caseBody = caseEntries.join("\n");

	return `#!/usr/bin/env bash
# Auto-generated by crust build — do not edit
set -e

source="$0"
while [ -L "$source" ]; do
\tlink_dir="$(cd "$(dirname "$source")" && pwd)"
\tsource="$(readlink "$source")"
\t# Resolve relative symlinks
\t[[ "$source" != /* ]] && source="$link_dir/$source"
done
dir="$(cd "$(dirname "$source")" && pwd)"
platform="$(uname -s)-$(uname -m)"

case "$platform" in
${caseBody}
\t*)
\t\techo "[${baseName}] Unsupported platform: $platform" >&2
\t\techo "[${baseName}] Please open an issue with your OS/CPU details." >&2
\t\texit 1
\t\t;;
esac

bin_path="$dir/$bin"

if [ ! -f "$bin_path" ]; then
\techo "[${baseName}] Prebuilt binary not found: $bin_path" >&2
\techo "[${baseName}] Expected binary for $platform: $bin" >&2
\techo "[${baseName}] Try reinstalling the package." >&2
\texit 1
fi

# Ensure the binary is executable
if [ ! -x "$bin_path" ]; then
\tchmod +x "$bin_path" 2>/dev/null || true
fi

exec "$bin_path" "$@"
`;
}

/**
 * Generate the Windows batch resolver script content (.cmd).
 *
 * The resolver checks `%PROCESSOR_ARCHITECTURE%` and dispatches
 * to the correct prebuilt `.exe` binary.
 *
 * @param baseName - The base binary name
 * @param targets - The list of targets that were built
 * @returns The .cmd resolver script as a string
 */
export function generateCmdResolver(baseName: string, targets: readonly BunTarget[]): string {
	const windowsTargets = targets.filter((t) => t.startsWith("bun-windows"));

	// If no Windows targets were built, generate a stub that tells the user
	if (windowsTargets.length === 0) {
		return `@echo off\r\necho [${baseName}] No Windows binary was built for this package. >&2\r\nexit /b 1\r\n`;
	}

	const windowsX64Target = windowsTargets.find(
		(t): t is BunTarget => t === "bun-windows-x64-baseline",
	);
	const windowsArm64Target = windowsTargets.find((t): t is BunTarget => t === "bun-windows-arm64");

	const x64Filename = windowsX64Target ? getBinaryFilename(baseName, windowsX64Target) : "";
	const arm64Filename = windowsArm64Target ? getBinaryFilename(baseName, windowsArm64Target) : "";

	// Build architecture dispatch lines.
	// CMD expands %var% at parse-time, so we cannot test a variable
	// that was set inside the same parenthesized block. Instead we
	// resolve the correct binary for each architecture at generation
	// time and emit flat, independent `if` statements.
	const archLines: string[] = [];

	if (arm64Filename) {
		archLines.push(`if /I "%host_arch%"=="ARM64" set "bin=${arm64Filename}"`);
	} else if (x64Filename) {
		// No native ARM64 binary — fall back to x64 under emulation
		archLines.push(`if /I "%host_arch%"=="ARM64" set "bin=${x64Filename}"`);
	}

	if (x64Filename) {
		archLines.push(`if /I "%host_arch%"=="AMD64" set "bin=${x64Filename}"`);
	}

	const archDispatch = archLines.join("\r\n");

	return `@echo off\r
rem Auto-generated by crust build -- do not edit\r
setlocal\r
set "dir=%~dp0"\r
set "bin="\r
set "host_arch=%PROCESSOR_ARCHITECTURE%"\r
\r
if /I "%PROCESSOR_ARCHITEW6432%"=="ARM64" set "host_arch=ARM64"\r
\r
${archDispatch}\r
\r
if "%bin%"=="" (\r
\techo [${baseName}] Unsupported Windows architecture: %host_arch% >&2\r
\techo [${baseName}] No matching Windows binary was built for this package. >&2\r
\texit /b 1\r
)\r
\r
set "bin_path=%dir%%bin%"\r
\r
if not exist "%bin_path%" (\r
\techo [${baseName}] Prebuilt binary not found: %bin_path% >&2\r
\techo [${baseName}] Try reinstalling the package. >&2\r
\texit /b 1\r
)\r
\r
"%bin_path%" %*\r
`;
}

/**
 * Write the resolver scripts to disk.
 *
 * Generates a POSIX shell script (the primary resolver) and a Windows
 * `.cmd` batch file alongside it for cross-platform npm distribution.
 *
 * @param resolverPath - Absolute path for the resolver file (no extension)
 * @param baseName - The base binary name
 * @param targets - The list of targets that were built
 */
function writeResolver(
	resolverPath: string,
	baseName: string,
	targets: readonly BunTarget[],
): void {
	const shellContent = generateResolver(baseName, targets);
	writeFileSync(resolverPath, shellContent, { mode: 0o755 });

	const cmdContent = generateCmdResolver(baseName, targets);
	writeFileSync(`${resolverPath}.cmd`, cmdContent);
}

export function resolveEnvFilePaths(cwd: string, envFiles: string[] | undefined): string[] {
	if (!envFiles || envFiles.length === 0) {
		return [];
	}

	return envFiles.map((envFile) => {
		const envPath = resolve(cwd, envFile);
		if (!existsSync(envPath)) {
			throw new Error(
				`Env file not found: ${envPath}\n  Specify a valid env file with --env-file <path>`,
			);
		}
		return envPath;
	});
}

// ────────────────────────────────────────────────────────────────────────────
// Build command
// ────────────────────────────────────────────────────────────────────────────

/**
 * The `crust build` command.
 *
 * Compiles a CLI entry file to standalone Bun executable(s).
 * By default, builds for all supported platforms and generates shell/CMD
 * resolver scripts for runtime-free dispatch.
 * Use `--target` to build for specific platform(s) only.
 *
 * @example
 * ```sh
 * crust build                                 # Build for all platforms + resolver scripts
 * crust build --entry src/main.ts             # Custom entry point
 * crust build --name my-tool                  # Output as dist/my-tool-*
 * crust build --no-minify                     # Disable minification
 * crust build --target bun-linux-x64-baseline              # Build only for Linux x64
 * crust build --target bun-linux-x64-baseline --target bun-darwin-arm64  # Specific platforms only
 * crust build --target bun-linux-x64-baseline --outfile ./my-cli     # Single target with custom output
 * crust build --outdir out                              # Output binaries to out/ directory
 * ```
 */
export const buildCommand = defineCommand(
	"build",
	{ description: "Compile your CLI to a standalone executable" },
	(command) =>
		command
			.flags(
				{
					name: "entry",
					type: "string",
					description: "Entry file path",
					default: "src/cli.ts",
					short: "e",
				},
				{
					name: "outfile",
					type: "string",
					description: "Output file path (single-target builds only)",
					short: "o",
				},
				{
					name: "name",
					type: "string",
					description: "Binary name (defaults to package.json name or entry filename)",
					short: "n",
				},
				{
					name: "minify",
					type: "boolean",
					description: "Minify the output",
					default: true,
				},
				{
					name: "target",
					type: "string",
					multiple: true,
					description:
						"Canonical Bun target(s) to compile for (e.g. bun-linux-x64-baseline, bun-darwin-arm64). Omit to build all.",
					short: "t",
				},
				{
					name: "outdir",
					type: "string",
					description: "Output directory for compiled binaries",
					default: "dist",
					short: "d",
				},
				{
					name: "resolver",
					type: "string",
					description: "Filename for the resolver script (multi-target builds, no extension)",
					default: "cli",
					short: "r",
				},
				{
					name: "validate",
					type: "boolean",
					description:
						"Materialize command definitions before compiling (disable with --no-validate)",
					default: true,
				},
				{
					name: "env-file",
					type: "string",
					multiple: true,
					description: "Explicit env file(s) used for build-time constants; repeatable",
				},
				{
					name: "package",
					type: "boolean",
					description: "Stage npm packages in dist/npm instead of raw binaries",
					default: false,
				},
				{
					name: "stage-dir",
					type: "string",
					description: "Directory to stage npm packages into when using --package",
					default: "dist/npm",
				},
			)
			.action(async ({ flags }) => {
				const cwd = process.cwd();

				// Resolve entry file path relative to cwd
				const entryPath = resolve(cwd, flags.entry);
				const envFiles = resolveEnvFilePaths(cwd, flags["env-file"]);

				// Verify entry file exists
				if (!existsSync(entryPath)) {
					throw new Error(
						`Entry file not found: ${entryPath}\n  Specify a valid entry file with --entry <path>`,
					);
				}

				if (flags.package && flags.outfile) {
					throw new Error(
						"--outfile cannot be used with --package.\n  Use --stage-dir to control the staged npm output directory.",
					);
				}
				const targets = resolveTargets(flags.target);
				if (!flags.package && flags.outfile && targets.length > 1) {
					throw new Error(
						"--outfile cannot be used when building for multiple targets.\n  Use --name to set the base binary name instead.",
					);
				}

				const outDir = resolve(cwd, flags.outdir);
				const prepared = flags.validate
					? await buildEntrypoint(entryPath, outDir, envFiles)
					: undefined;
				for (const extension of prepared?.builtExtensions ?? []) {
					console.log(`${green("✓")} ${extension}`);
				}

				if (flags.package) {
					const { runDistributeBuild } = await import("../utils/distribute.ts");
					await runDistributeBuild({
						cwd,
						entry: flags.entry,
						name: flags.name,
						minify: flags.minify,
						target: flags.target,
						stageDir: flags["stage-dir"],
						envFiles,
						artifactOutDir: prepared?.builtExtensions.length ? outDir : undefined,
					});
					return;
				}

				if (targets.length === 1) {
					// Single-target build: one binary, no resolver
					const outfilePath = resolveOutfile(
						flags.outfile,
						flags.name,
						entryPath,
						cwd,
						flags.outdir,
					);

					console.log(`Building ${dim(entryPath)} ${cyan("→")} ${dim(outfilePath)}...`);
					await execBuild(entryPath, outfilePath, flags.minify, targets[0], envFiles);
					console.log(`${green("✓")} Built successfully: ${outfilePath}`);
				} else {
					// Multi-target build: multiple binaries + shell/CMD resolvers
					const baseName = resolveBaseName(flags.name, entryPath, cwd);

					console.log(`Building ${dim(entryPath)} for ${bold(`${targets.length}`)} target(s)...`);

					const results: string[] = [];
					for (const target of targets) {
						const targetOutfile = resolve(cwd, flags.outdir, getBinaryFilename(baseName, target));

						console.log(`  ${cyan("→")} ${bold(target)}: ${dim(targetOutfile)}`);
						await execBuild(entryPath, targetOutfile, flags.minify, target, envFiles);
						results.push(targetOutfile);
					}

					// Generate resolver scripts
					const resolverPath = resolve(cwd, flags.outdir, flags.resolver);
					writeResolver(resolverPath, baseName, targets);

					console.log(`\n${green("✓")} Built ${bold(`${results.length}`)} target(s) successfully:`);
					for (const r of results) {
						console.log(`  ${r}`);
					}
					console.log(`\n${dim("Resolver:")} ${resolverPath} ${dim(`(+ ${resolverPath}.cmd)`)}`);
				}
			}),
);
