import { existsSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import { defineCommand, type InvocationIO } from "@crustjs/core";
import { bold, cyan, dim, green } from "@crustjs/style";
import { isJsonObject, type JsonValue } from "@crustjs/utils/json";

import {
	binaryFilename,
	BUILD_RUNTIMES,
	type BuildRuntime,
	BUN_TARGETS,
	type BunTarget,
	DENO_TARGETS,
	type DenoTarget,
	execBuild,
	execDenoBuild,
	execNodeBuild,
	resolveBaseName,
	readUserPackageJson,
	resolveTargets,
	buildEntrypoint,
	type TargetTable,
} from "../utils/build-helpers.ts";
import { runDistributeBuild } from "../utils/distribute.ts";

/**
 * Resolve the output file path for a single-target build.
 *
 * Priority: --outfile > --name (as ./<outdir>/<name>) > package.json name > entry filename
 *
 * @param outfile - Explicit output file path from --outfile flag
 * @param name - Binary name from --name flag
 * @param entry - Resolved entry file path
 * @param cwd - Current working directory
 * @param outdir - Output directory
 * @param ext - Extension appended to a derived base name (e.g. ".js" for Node)
 * @returns The resolved output file path
 */
function resolveOutfile(
	outfile: string | undefined,
	name: string | undefined,
	entry: string,
	cwd: string,
	outdir: string,
	ext: string,
	packageJson: JsonValue | undefined,
): string {
	// Explicit --outfile takes highest priority
	if (outfile) {
		return resolve(cwd, outfile);
	}

	const baseName = resolveBaseName(name, entry, cwd, packageJson);
	return resolve(cwd, outdir, baseName.endsWith(ext) ? baseName : baseName + ext);
}

function getConfiguredRuntime(pkg: JsonValue): JsonValue | undefined {
	if (!isJsonObject(pkg)) return undefined;
	const crust = pkg.crust;
	return crust !== undefined && isJsonObject(crust) ? crust.runtime : undefined;
}

function isBuildRuntime(value: JsonValue): value is BuildRuntime {
	return typeof value === "string" && BUILD_RUNTIMES.some((runtime) => runtime === value);
}

function resolveBuildRuntimeFromPackageJson(
	pkg: JsonValue | undefined,
	override?: BuildRuntime,
): BuildRuntime {
	// --runtime is validated by the flag's `choices`; no re-check needed here.
	if (override !== undefined) return override;
	if (pkg === undefined) return "bun";
	const configured = getConfiguredRuntime(pkg);
	if (configured === undefined) return "bun";
	if (isBuildRuntime(configured)) return configured;
	throw new Error(
		`Invalid package.json crust.runtime ${JSON.stringify(configured)}. Valid runtimes: ${BUILD_RUNTIMES.join(", ")}`,
	);
}

// ────────────────────────────────────────────────────────────────────────────
// Shell resolver generator (Unix + Windows)
// ────────────────────────────────────────────────────────────────────────────

/**
 * Generate the shell resolver script content (Unix).
 *
 * The resolver detects the platform via `uname -s` and `uname -m`,
 * maps to the correct prebuilt binary, ensures execute permissions,
 * and execs it with all arguments forwarded.
 *
 * @param baseName - The base binary name
 * @param targets - The list of targets that were built
 * @returns The shell resolver script as a string
 */
export function generateResolverFor<T extends string>(
	table: TargetTable<T>,
	baseName: string,
	targets: readonly T[],
): string {
	const caseEntries: string[] = [];
	for (const target of targets) {
		const info = table.info[target];
		if (info.os === "win32") continue;
		caseEntries.push(`\t${info.unameKey}) bin="${binaryFilename(table, baseName, target)}" ;;`);
	}
	const caseBody = caseEntries.join("\n");

	return `#!/usr/bin/env bash
# Auto-generated by crust build — do not edit
set -e

source="$0"
while [ -L "$source" ]; do
\tlink_dir="$(cd "$(dirname "$source")" && pwd)"
\tsource="$(readlink "$source")"
\t# Resolve relative symlinks
\t[[ "$source" != /* ]] && source="$link_dir/$source"
done
dir="$(cd "$(dirname "$source")" && pwd)"
platform="$(uname -s)-$(uname -m)"

case "$platform" in
${caseBody}
\t*)
\t\techo "[${baseName}] Unsupported platform: $platform" >&2
\t\techo "[${baseName}] Please open an issue with your OS/CPU details." >&2
\t\texit 1
\t\t;;
esac

bin_path="$dir/$bin"

if [ ! -f "$bin_path" ]; then
\techo "[${baseName}] Prebuilt binary not found: $bin_path" >&2
\techo "[${baseName}] Expected binary for $platform: $bin" >&2
\techo "[${baseName}] Try reinstalling the package." >&2
\texit 1
fi

# Ensure the binary is executable
if [ ! -x "$bin_path" ]; then
\tchmod +x "$bin_path" 2>/dev/null || true
fi

exec "$bin_path" "$@"
`;
}

/**
 * Generate the Windows batch resolver script content (.cmd).
 *
 * The resolver checks `%PROCESSOR_ARCHITECTURE%` and dispatches
 * to the correct prebuilt `.exe` binary.
 *
 * @param baseName - The base binary name
 * @param targets - The list of targets that were built
 * @returns The .cmd resolver script as a string
 */
export function generateCmdResolverFor<T extends string>(
	table: TargetTable<T>,
	baseName: string,
	targets: readonly T[],
): string {
	const windowsTargets = targets.filter((target) => table.info[target].os === "win32");

	if (windowsTargets.length === 0) {
		return `@echo off\r\necho [${baseName}] No Windows binary was built for this package. >&2\r\nexit /b 1\r\n`;
	}

	const windowsX64Target = windowsTargets.find((target) => table.info[target].cpu === "x64");
	const windowsArm64Target = windowsTargets.find((target) => table.info[target].cpu === "arm64");

	const x64Filename = windowsX64Target ? binaryFilename(table, baseName, windowsX64Target) : "";
	const arm64Filename = windowsArm64Target
		? binaryFilename(table, baseName, windowsArm64Target)
		: "";

	// Build architecture dispatch lines.
	// CMD expands %var% at parse-time, so we cannot test a variable
	// that was set inside the same parenthesized block. Instead we
	// resolve the correct binary for each architecture at generation
	// time and emit flat, independent `if` statements.
	const archLines: string[] = [];

	if (arm64Filename) {
		archLines.push(`if /I "%host_arch%"=="ARM64" set "bin=${arm64Filename}"`);
	} else if (x64Filename) {
		// No native ARM64 binary — fall back to x64 under emulation
		archLines.push(`if /I "%host_arch%"=="ARM64" set "bin=${x64Filename}"`);
	}

	if (x64Filename) {
		archLines.push(`if /I "%host_arch%"=="AMD64" set "bin=${x64Filename}"`);
	}

	const archDispatch = archLines.join("\r\n");

	return `@echo off\r
rem Auto-generated by crust build -- do not edit\r
setlocal\r
set "dir=%~dp0"\r
set "bin="\r
set "host_arch=%PROCESSOR_ARCHITECTURE%"\r
\r
if /I "%PROCESSOR_ARCHITEW6432%"=="ARM64" set "host_arch=ARM64"\r
\r
${archDispatch}\r
\r
if "%bin%"=="" (\r
\techo [${baseName}] Unsupported Windows architecture: %host_arch% >&2\r
\techo [${baseName}] No matching Windows binary was built for this package. >&2\r
\texit /b 1\r
)\r
\r
set "bin_path=%dir%%bin%"\r
\r
if not exist "%bin_path%" (\r
\techo [${baseName}] Prebuilt binary not found: %bin_path% >&2\r
\techo [${baseName}] Try reinstalling the package. >&2\r
\texit /b 1\r
)\r
\r
"%bin_path%" %*\r
`;
}

/**
 * Write the resolver scripts to disk.
 *
 * Generates a POSIX shell script (the primary resolver) and a Windows
 * `.cmd` batch file alongside it for cross-platform npm distribution.
 *
 * @param resolverPath - Absolute path for the resolver file (no extension)
 * @param baseName - The base binary name
 * @param targets - The list of targets that were built
 */
export function writeResolver<T extends string>(
	table: TargetTable<T>,
	resolverPath: string,
	baseName: string,
	targets: readonly T[],
): void {
	writeFileSync(resolverPath, generateResolverFor(table, baseName, targets), { mode: 0o755 });
	writeFileSync(`${resolverPath}.cmd`, generateCmdResolverFor(table, baseName, targets));
}

type BinaryOutput<T extends string> = { target: T; outfilePath: string };
type ResolverPlan = { path: string; baseName: string };
type PlannedBinaryOutputs<T extends string> = {
	outputs: Array<BinaryOutput<T>>;
	resolver: ResolverPlan;
};

type BinaryExecutor<T extends string> = {
	execute: (
		entry: string,
		outfile: string,
		target: T,
		envFiles: readonly string[],
	) => Promise<void>;
	writeResolver: (path: string, baseName: string, targets: readonly T[]) => void;
};

async function buildBinaryOutputs<T extends string>(
	plan: {
		entryPath: string;
		envFiles: readonly string[];
		outputs: readonly BinaryOutput<T>[];
		resolver: ResolverPlan;
	},
	executor: BinaryExecutor<T>,
	io: InvocationIO,
): Promise<void> {
	if (plan.outputs.length === 1) {
		const output = plan.outputs[0]!;
		io.stdout(`Building ${dim(plan.entryPath)} ${cyan("→")} ${dim(output.outfilePath)}...`);
		await executor.execute(plan.entryPath, output.outfilePath, output.target, plan.envFiles);
		io.stdout(`${green("✓")} Built successfully: ${output.outfilePath}`);
		return;
	}

	io.stdout(`Building ${dim(plan.entryPath)} for ${bold(`${plan.outputs.length}`)} target(s)...`);
	for (const output of plan.outputs) {
		io.stdout(`  ${cyan("→")} ${bold(output.target)}: ${dim(output.outfilePath)}`);
		await executor.execute(plan.entryPath, output.outfilePath, output.target, plan.envFiles);
	}

	const resolver = plan.resolver;
	const targets = plan.outputs.map((output) => output.target);
	executor.writeResolver(resolver.path, resolver.baseName, targets);
	io.stdout(`\n${green("✓")} Built ${bold(`${plan.outputs.length}`)} target(s) successfully:`);
	for (const output of plan.outputs) io.stdout(`  ${output.outfilePath}`);
	io.stdout(`\n${dim("Resolver:")} ${resolver.path} ${dim(`(+ ${resolver.path}.cmd)`)}`);
}

export function resolveEnvFilePaths(cwd: string, envFiles: string[] | undefined): string[] {
	if (!envFiles || envFiles.length === 0) {
		return [];
	}

	return envFiles.map((envFile) => {
		const envPath = resolve(cwd, envFile);
		if (!existsSync(envPath)) {
			throw new Error(
				`Env file not found: ${envPath}\n  Specify a valid env file with --env-file <path>`,
			);
		}
		return envPath;
	});
}

export type BuildFlags = {
	entry: string;
	outfile?: string;
	name?: string;
	minify?: boolean;
	runtime?: BuildRuntime;
	target?: string[];
	outdir: string;
	resolver: string;
	validate: boolean;
	"env-file"?: string[];
	package: boolean;
	"stage-dir": string;
};

type CommonBuildPlan = {
	cwd: string;
	userPackageJson: JsonValue | undefined;
	entryPath: string;
	envFiles: string[];
	outDir: string;
	validate: boolean;
	minify: boolean;
	warnings: string[];
};

type BunBuildPlan = CommonBuildPlan &
	(
		| {
				runtime: "bun";
				mode: "package";
				name?: string;
				targets: BunTarget[];
				stageDir: string;
		  }
		| {
				runtime: "bun";
				mode: "binary";
				outputs: Array<BinaryOutput<BunTarget>>;
				resolver: ResolverPlan;
		  }
	);

type DenoBuildPlan = CommonBuildPlan & {
	runtime: "deno";
	mode: "binary";
	outputs: Array<BinaryOutput<DenoTarget>>;
	resolver: ResolverPlan;
};

type NodeBuildPlan = CommonBuildPlan & {
	runtime: "node";
	mode: "node";
	outfilePath: string;
};

export type BuildPlan = BunBuildPlan | DenoBuildPlan | NodeBuildPlan;

function planBinaryOutputs<T extends string>(options: {
	table: TargetTable<T>;
	targets: T[];
	flags: BuildFlags;
	cwd: string;
	entryPath: string;
	packageJson: JsonValue | undefined;
}): PlannedBinaryOutputs<T> {
	const baseName = resolveBaseName(
		options.flags.name,
		options.entryPath,
		options.cwd,
		options.packageJson,
	);
	const resolver = {
		path: resolve(options.cwd, options.flags.outdir, options.flags.resolver),
		baseName,
	};
	if (options.targets.length === 1) {
		const target = options.targets[0]!;
		const ext = options.table.info[target].os === "win32" ? ".exe" : "";
		const resolved = resolveOutfile(
			options.flags.outfile,
			options.flags.name,
			options.entryPath,
			options.cwd,
			options.flags.outdir,
			"",
			options.packageJson,
		);
		return {
			outputs: [
				{ target, outfilePath: ext && !resolved.endsWith(ext) ? resolved + ext : resolved },
			],
			resolver,
		};
	}

	return {
		outputs: options.targets.map((target) => ({
			target,
			outfilePath: resolve(
				options.cwd,
				options.flags.outdir,
				binaryFilename(options.table, baseName, target),
			),
		})),
		resolver,
	};
}

export function planBuild(flags: BuildFlags, cwd: string): BuildPlan {
	const userPackageJson = readUserPackageJson(cwd);
	const runtime = resolveBuildRuntimeFromPackageJson(userPackageJson, flags.runtime);
	const entryPath = resolve(cwd, flags.entry);
	const envFiles = resolveEnvFilePaths(cwd, flags["env-file"]);

	if (!existsSync(entryPath)) {
		throw new Error(
			`Entry file not found: ${entryPath}\n  Specify a valid entry file with --entry <path>`,
		);
	}
	if (flags.package && runtime === "deno") {
		throw new Error(
			"--package does not yet support Deno builds.\n  Deno per-platform npm staging is reserved for a follow-up; build a specific target without --package for now.",
		);
	}
	if (flags.package && runtime === "node") {
		throw new Error(
			"--package does not apply to Node builds.\n  Publish the generated JavaScript artifact as a normal npm package.",
		);
	}
	if (flags.package && flags.outfile) {
		throw new Error(
			"--outfile cannot be used with --package.\n  Use --stage-dir to control the staged npm output directory.",
		);
	}
	if (runtime === "node" && flags.target?.length) {
		throw new Error(
			"--target cannot be used with --runtime node.\n  Node builds produce one portable JavaScript artifact.",
		);
	}
	if (runtime === "deno" && flags.minify) {
		throw new Error(
			"--minify is not supported with --runtime deno.\n  deno compile has no minification step; drop the flag.",
		);
	}
	if (runtime === "deno" && envFiles.length > 0) {
		throw new Error(
			"--env-file is not supported with --runtime deno.\n" +
				"  deno compile embeds every variable from the file into the binary — secrets included —\n" +
				"  with no PUBLIC_* filter. Load configuration at runtime instead (e.g. deno run --env-file).",
		);
	}

	const minify = runtime === "deno" ? false : (flags.minify ?? true);
	const outDir = flags.outfile ? dirname(resolve(cwd, flags.outfile)) : resolve(cwd, flags.outdir);
	const common = {
		cwd,
		userPackageJson,
		entryPath,
		envFiles,
		outDir,
		validate: flags.validate,
		minify,
		warnings:
			runtime === "node" && flags.resolver !== "cli"
				? [
						"Warning: --resolver is ignored with --runtime node; Node builds produce a single JavaScript artifact.",
					]
				: [],
	};

	if (runtime === "node") {
		return {
			...common,
			runtime,
			mode: "node",
			outfilePath: resolveOutfile(
				flags.outfile,
				flags.name,
				entryPath,
				cwd,
				flags.outdir,
				".js",
				userPackageJson,
			),
		};
	}
	if (runtime === "bun") {
		const targets = resolveTargets(BUN_TARGETS, flags.target);
		if (!flags.package && flags.outfile && targets.length > 1) {
			throw new Error(
				"--outfile cannot be used when building for multiple targets.\n  Use --name to set the base binary name instead.",
			);
		}
		if (flags.package) {
			return {
				...common,
				runtime,
				mode: "package",
				...(flags.name === undefined ? {} : { name: flags.name }),
				targets,
				stageDir: resolve(cwd, flags["stage-dir"]),
			};
		}
		return {
			...common,
			runtime,
			mode: "binary",
			...planBinaryOutputs({
				table: BUN_TARGETS,
				targets,
				flags,
				cwd,
				entryPath,
				packageJson: userPackageJson,
			}),
		};
	}

	const targets = resolveTargets(DENO_TARGETS, flags.target);
	if (flags.outfile && targets.length > 1) {
		throw new Error(
			"--outfile cannot be used when building for multiple targets.\n  Use --name to set the base binary name instead.",
		);
	}
	return {
		...common,
		runtime,
		mode: "binary",
		...planBinaryOutputs({
			table: DENO_TARGETS,
			targets,
			flags,
			cwd,
			entryPath,
			packageJson: userPackageJson,
		}),
	};
}

// ────────────────────────────────────────────────────────────────────────────
// Build command
// ────────────────────────────────────────────────────────────────────────────

/**
 * The `crust build` command.
 *
 * Builds a CLI entry for Bun, Deno, or Node.
 * Bun and Deno produce standalone executables and multi-platform resolvers;
 * Node produces one executable JavaScript bundle.
 *
 * @example
 * ```sh
 * crust build                                 # Build for all platforms + resolver scripts
 * crust build --entry src/main.ts             # Custom entry point
 * crust build --name my-tool                  # Output as dist/my-tool-*
 * crust build --no-minify                     # Disable minification
 * crust build --target bun-linux-x64-baseline              # Build only for Linux x64
 * crust build --target bun-linux-x64-baseline --target bun-darwin-arm64  # Specific platforms only
 * crust build --target bun-linux-x64-baseline --outfile ./my-cli     # Single target with custom output
 * crust build --runtime deno --target aarch64-apple-darwin
 * crust build --runtime node --outdir out               # Output out/<name>.js
 * ```
 */
export const buildCommand = defineCommand(
	"build",
	{ description: "Build your CLI for Bun, Deno, or Node" },
	(command) =>
		command
			.flags(
				{
					name: "entry",
					type: "string",
					description: "Entry file path",
					default: "src/cli.ts",
					short: "e",
				},
				{
					name: "outfile",
					type: "string",
					description: "Output file path (single-target builds only)",
					short: "o",
				},
				{
					name: "name",
					type: "string",
					description: "Binary name (defaults to package.json name or entry filename)",
					short: "n",
				},
				{
					name: "minify",
					type: "boolean",
					// No default: deno builds must distinguish an explicit --minify (error)
					// from the implicit bun/node default (true, applied below).
					description: "Minify the output (default for bun and node; unsupported for deno)",
				},
				{
					name: "runtime",
					type: "string",
					choices: BUILD_RUNTIMES,
					description: "Build runtime (overrides package.json crust.runtime; defaults to bun)",
				},
				{
					name: "target",
					type: "string",
					multiple: true,
					description: "Canonical compiler target(s). Omit to build all platforms for Bun or Deno.",
					short: "t",
				},
				{
					name: "outdir",
					type: "string",
					description: "Output directory for build artifacts",
					default: "dist",
					short: "d",
				},
				{
					name: "resolver",
					type: "string",
					description: "Filename for the resolver script (multi-target builds, no extension)",
					default: "cli",
					short: "r",
				},
				{
					name: "validate",
					type: "boolean",
					description:
						"Materialize command definitions before compiling; --no-validate also skips Extension build hooks",
					default: true,
				},
				{
					name: "env-file",
					type: "string",
					multiple: true,
					description: "Explicit env file(s) used for build-time constants; repeatable",
				},
				{
					name: "package",
					type: "boolean",
					description: "Stage per-platform Bun npm packages in dist/npm",
					default: false,
				},
				{
					name: "stage-dir",
					type: "string",
					description: "Directory to stage npm packages into when using --package",
					default: "dist/npm",
				},
			)
			.action(async ({ flags, stdout, stderr }) => {
				const cwd = process.cwd();
				const io = { stdout, stderr };
				const plan = planBuild(flags, cwd);
				for (const warning of plan.warnings) stderr(warning);
				if (plan.validate) {
					await buildEntrypoint(plan.entryPath, plan.outDir, plan.envFiles, io, cwd);
				}

				if (plan.runtime === "bun" && plan.mode === "package") {
					await runDistributeBuild(plan, { io });
					return;
				}

				if (plan.runtime === "node") {
					stdout(`Building ${dim(plan.entryPath)} ${cyan("→")} ${dim(plan.outfilePath)}...`);
					await execNodeBuild(plan.entryPath, plan.outfilePath, plan.minify, plan.envFiles, cwd);
					stdout(`${green("✓")} Built successfully: ${plan.outfilePath}`);
					return;
				}

				if (plan.runtime === "bun") {
					await buildBinaryOutputs(
						plan,
						{
							execute: (entry, outfile, target, envFiles) =>
								execBuild(entry, outfile, plan.minify, target, envFiles, cwd),
							writeResolver: (path, baseName, targets) =>
								writeResolver(BUN_TARGETS, path, baseName, targets),
						},
						io,
					);
					return;
				}
				await buildBinaryOutputs(
					plan,
					{
						execute: (entry, outfile, target) => execDenoBuild(entry, outfile, target, cwd),
						writeResolver: (path, baseName, targets) =>
							writeResolver(DENO_TARGETS, path, baseName, targets),
					},
					io,
				);
			}),
);
