import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import { defineCommand } from "@crustjs/core";
import { bold, cyan, dim, green } from "@crustjs/style";

import {
	BUILD_RUNTIMES,
	type BuildRuntime,
	type BunTarget,
	DENO_TARGET_INFO,
	type DenoTarget,
	execBuild,
	execDenoBuild,
	execNodeBuild,
	getBinaryFilename,
	getDenoBinaryFilename,
	resolveBaseName,
	resolveDenoTargets,
	resolveTargets,
	TARGET_INFO,
	buildEntrypoint,
	type ResolverTargetInfo,
} from "../utils/build-helpers.ts";

/**
 * Resolve the output file path for a single-target build.
 *
 * Priority: --outfile > --name (as ./<outdir>/<name>) > package.json name > entry filename
 *
 * @param outfile - Explicit output file path from --outfile flag
 * @param name - Binary name from --name flag
 * @param entry - Resolved entry file path
 * @param cwd - Current working directory
 * @param outdir - Output directory
 * @returns The resolved output file path
 */
export function resolveOutfile(
	outfile: string | undefined,
	name: string | undefined,
	entry: string,
	cwd: string,
	outdir: string,
): string {
	// Explicit --outfile takes highest priority
	if (outfile) {
		return resolve(cwd, outfile);
	}

	const baseName = resolveBaseName(name, entry, cwd);
	return resolve(cwd, outdir, baseName);
}

export function resolveNodeOutfile(
	outfile: string | undefined,
	name: string | undefined,
	entry: string,
	cwd: string,
	outdir: string,
): string {
	if (outfile) return resolve(cwd, outfile);
	const baseName = resolveBaseName(name, entry, cwd);
	return resolve(cwd, outdir, baseName.endsWith(".js") ? baseName : `${baseName}.js`);
}

export function resolveBuildRuntime(cwd: string, override?: string): BuildRuntime {
	if (override !== undefined) {
		if ((BUILD_RUNTIMES as readonly string[]).includes(override)) return override as BuildRuntime;
		throw new Error(`Unknown runtime "${override}". Valid runtimes: ${BUILD_RUNTIMES.join(", ")}`);
	}

	const packagePath = resolve(cwd, "package.json");
	if (!existsSync(packagePath)) return "bun";
	let pkg: { crust?: { runtime?: unknown } };
	try {
		pkg = JSON.parse(readFileSync(packagePath, "utf8")) as { crust?: { runtime?: unknown } };
	} catch {
		// Malformed package.json: legacy builds tolerated this (resolveBaseName falls
		// through), so keep default-bun builds working — but say so, since a
		// configured crust.runtime in that file would be silently ignored.
		console.warn(`Warning: could not parse ${packagePath}; defaulting to the bun runtime.`);
		return "bun";
	}
	const configured = pkg.crust?.runtime;
	if (configured === undefined) return "bun";
	if (
		typeof configured === "string" &&
		(BUILD_RUNTIMES as readonly string[]).includes(configured)
	) {
		return configured as BuildRuntime;
	}
	throw new Error(
		`Invalid package.json crust.runtime ${JSON.stringify(configured)}. Valid runtimes: ${BUILD_RUNTIMES.join(", ")}`,
	);
}

// ────────────────────────────────────────────────────────────────────────────
// Shell resolver generator (Unix + Windows)
// ────────────────────────────────────────────────────────────────────────────

/**
 * Generate the shell resolver script content (Unix).
 *
 * The resolver detects the platform via `uname -s` and `uname -m`,
 * maps to the correct prebuilt binary, ensures execute permissions,
 * and execs it with all arguments forwarded.
 *
 * @param baseName - The base binary name
 * @param targets - The list of targets that were built
 * @returns The shell resolver script as a string
 */
function generateResolverFor<T extends string>(
	baseName: string,
	targets: readonly T[],
	targetInfo: Record<T, ResolverTargetInfo>,
	getFilename: (baseName: string, target: T) => string,
): string {
	const caseEntries: string[] = [];
	for (const target of targets) {
		const info = targetInfo[target];
		if (info.os === "win32") continue;
		caseEntries.push(`\t${info.unameKey}) bin="${getFilename(baseName, target)}" ;;`);
	}
	const caseBody = caseEntries.join("\n");

	return `#!/usr/bin/env bash
# Auto-generated by crust build — do not edit
set -e

source="$0"
while [ -L "$source" ]; do
\tlink_dir="$(cd "$(dirname "$source")" && pwd)"
\tsource="$(readlink "$source")"
\t# Resolve relative symlinks
\t[[ "$source" != /* ]] && source="$link_dir/$source"
done
dir="$(cd "$(dirname "$source")" && pwd)"
platform="$(uname -s)-$(uname -m)"

case "$platform" in
${caseBody}
\t*)
\t\techo "[${baseName}] Unsupported platform: $platform" >&2
\t\techo "[${baseName}] Please open an issue with your OS/CPU details." >&2
\t\texit 1
\t\t;;
esac

bin_path="$dir/$bin"

if [ ! -f "$bin_path" ]; then
\techo "[${baseName}] Prebuilt binary not found: $bin_path" >&2
\techo "[${baseName}] Expected binary for $platform: $bin" >&2
\techo "[${baseName}] Try reinstalling the package." >&2
\texit 1
fi

# Ensure the binary is executable
if [ ! -x "$bin_path" ]; then
\tchmod +x "$bin_path" 2>/dev/null || true
fi

exec "$bin_path" "$@"
`;
}

export function generateResolver(baseName: string, targets: readonly BunTarget[]): string {
	return generateResolverFor(baseName, targets, TARGET_INFO, getBinaryFilename);
}

export function generateDenoResolver(baseName: string, targets: readonly DenoTarget[]): string {
	return generateResolverFor(baseName, targets, DENO_TARGET_INFO, getDenoBinaryFilename);
}

/**
 * Generate the Windows batch resolver script content (.cmd).
 *
 * The resolver checks `%PROCESSOR_ARCHITECTURE%` and dispatches
 * to the correct prebuilt `.exe` binary.
 *
 * @param baseName - The base binary name
 * @param targets - The list of targets that were built
 * @returns The .cmd resolver script as a string
 */
function generateCmdResolverFor<T extends string>(
	baseName: string,
	targets: readonly T[],
	targetInfo: Record<T, ResolverTargetInfo>,
	getFilename: (baseName: string, target: T) => string,
): string {
	const windowsTargets = targets.filter((target) => targetInfo[target].os === "win32");

	if (windowsTargets.length === 0) {
		return `@echo off\r\necho [${baseName}] No Windows binary was built for this package. >&2\r\nexit /b 1\r\n`;
	}

	const windowsX64Target = windowsTargets.find((target) => targetInfo[target].cpu === "x64");
	const windowsArm64Target = windowsTargets.find((target) => targetInfo[target].cpu === "arm64");

	const x64Filename = windowsX64Target ? getFilename(baseName, windowsX64Target) : "";
	const arm64Filename = windowsArm64Target ? getFilename(baseName, windowsArm64Target) : "";

	// Build architecture dispatch lines.
	// CMD expands %var% at parse-time, so we cannot test a variable
	// that was set inside the same parenthesized block. Instead we
	// resolve the correct binary for each architecture at generation
	// time and emit flat, independent `if` statements.
	const archLines: string[] = [];

	if (arm64Filename) {
		archLines.push(`if /I "%host_arch%"=="ARM64" set "bin=${arm64Filename}"`);
	} else if (x64Filename) {
		// No native ARM64 binary — fall back to x64 under emulation
		archLines.push(`if /I "%host_arch%"=="ARM64" set "bin=${x64Filename}"`);
	}

	if (x64Filename) {
		archLines.push(`if /I "%host_arch%"=="AMD64" set "bin=${x64Filename}"`);
	}

	const archDispatch = archLines.join("\r\n");

	return `@echo off\r
rem Auto-generated by crust build -- do not edit\r
setlocal\r
set "dir=%~dp0"\r
set "bin="\r
set "host_arch=%PROCESSOR_ARCHITECTURE%"\r
\r
if /I "%PROCESSOR_ARCHITEW6432%"=="ARM64" set "host_arch=ARM64"\r
\r
${archDispatch}\r
\r
if "%bin%"=="" (\r
\techo [${baseName}] Unsupported Windows architecture: %host_arch% >&2\r
\techo [${baseName}] No matching Windows binary was built for this package. >&2\r
\texit /b 1\r
)\r
\r
set "bin_path=%dir%%bin%"\r
\r
if not exist "%bin_path%" (\r
\techo [${baseName}] Prebuilt binary not found: %bin_path% >&2\r
\techo [${baseName}] Try reinstalling the package. >&2\r
\texit /b 1\r
)\r
\r
"%bin_path%" %*\r
`;
}

export function generateCmdResolver(baseName: string, targets: readonly BunTarget[]): string {
	return generateCmdResolverFor(baseName, targets, TARGET_INFO, getBinaryFilename);
}

export function generateDenoCmdResolver(baseName: string, targets: readonly DenoTarget[]): string {
	return generateCmdResolverFor(baseName, targets, DENO_TARGET_INFO, getDenoBinaryFilename);
}

/**
 * Write the resolver scripts to disk.
 *
 * Generates a POSIX shell script (the primary resolver) and a Windows
 * `.cmd` batch file alongside it for cross-platform npm distribution.
 *
 * @param resolverPath - Absolute path for the resolver file (no extension)
 * @param baseName - The base binary name
 * @param targets - The list of targets that were built
 */
function writeResolver(
	resolverPath: string,
	baseName: string,
	targets: readonly BunTarget[],
): void {
	writeFileSync(resolverPath, generateResolver(baseName, targets), { mode: 0o755 });
	writeFileSync(`${resolverPath}.cmd`, generateCmdResolver(baseName, targets));
}

function writeDenoResolver(
	resolverPath: string,
	baseName: string,
	targets: readonly DenoTarget[],
): void {
	writeFileSync(resolverPath, generateDenoResolver(baseName, targets), { mode: 0o755 });
	writeFileSync(`${resolverPath}.cmd`, generateDenoCmdResolver(baseName, targets));
}

type BinaryBuildOptions<T extends string> = {
	entryPath: string;
	outfile?: string;
	name?: string;
	cwd: string;
	outdir: string;
	resolver: string;
	targets: readonly T[];
	envFiles: readonly string[];
	getFilename: (baseName: string, target: T) => string;
	execute: (
		entry: string,
		outfile: string,
		target: T,
		envFiles: readonly string[],
	) => Promise<void>;
	writeResolver: (path: string, baseName: string, targets: readonly T[]) => void;
};

async function buildBinaryOutputs<T extends string>(options: BinaryBuildOptions<T>): Promise<void> {
	if (options.targets.length === 1) {
		const outfilePath = resolveOutfile(
			options.outfile,
			options.name,
			options.entryPath,
			options.cwd,
			options.outdir,
		);
		console.log(`Building ${dim(options.entryPath)} ${cyan("→")} ${dim(outfilePath)}...`);
		await options.execute(options.entryPath, outfilePath, options.targets[0]!, options.envFiles);
		console.log(`${green("✓")} Built successfully: ${outfilePath}`);
		return;
	}

	const baseName = resolveBaseName(options.name, options.entryPath, options.cwd);
	console.log(
		`Building ${dim(options.entryPath)} for ${bold(`${options.targets.length}`)} target(s)...`,
	);
	const results: string[] = [];
	for (const target of options.targets) {
		const targetOutfile = resolve(
			options.cwd,
			options.outdir,
			options.getFilename(baseName, target),
		);
		console.log(`  ${cyan("→")} ${bold(target)}: ${dim(targetOutfile)}`);
		await options.execute(options.entryPath, targetOutfile, target, options.envFiles);
		results.push(targetOutfile);
	}

	const resolverPath = resolve(options.cwd, options.outdir, options.resolver);
	options.writeResolver(resolverPath, baseName, options.targets);
	console.log(`\n${green("✓")} Built ${bold(`${results.length}`)} target(s) successfully:`);
	for (const result of results) console.log(`  ${result}`);
	console.log(`\n${dim("Resolver:")} ${resolverPath} ${dim(`(+ ${resolverPath}.cmd)`)}`);
}

export function resolveEnvFilePaths(cwd: string, envFiles: string[] | undefined): string[] {
	if (!envFiles || envFiles.length === 0) {
		return [];
	}

	return envFiles.map((envFile) => {
		const envPath = resolve(cwd, envFile);
		if (!existsSync(envPath)) {
			throw new Error(
				`Env file not found: ${envPath}\n  Specify a valid env file with --env-file <path>`,
			);
		}
		return envPath;
	});
}

// ────────────────────────────────────────────────────────────────────────────
// Build command
// ────────────────────────────────────────────────────────────────────────────

/**
 * The `crust build` command.
 *
 * Builds a CLI entry for Bun, Deno, or Node.
 * Bun and Deno produce standalone executables and multi-platform resolvers;
 * Node produces one executable JavaScript bundle.
 *
 * @example
 * ```sh
 * crust build                                 # Build for all platforms + resolver scripts
 * crust build --entry src/main.ts             # Custom entry point
 * crust build --name my-tool                  # Output as dist/my-tool-*
 * crust build --no-minify                     # Disable minification
 * crust build --target bun-linux-x64-baseline              # Build only for Linux x64
 * crust build --target bun-linux-x64-baseline --target bun-darwin-arm64  # Specific platforms only
 * crust build --target bun-linux-x64-baseline --outfile ./my-cli     # Single target with custom output
 * crust build --runtime deno --target aarch64-apple-darwin
 * crust build --runtime node --outdir out               # Output out/<name>.js
 * ```
 */
export const buildCommand = defineCommand(
	"build",
	{ description: "Build your CLI for Bun, Deno, or Node" },
	(command) =>
		command
			.flags(
				{
					name: "entry",
					type: "string",
					description: "Entry file path",
					default: "src/cli.ts",
					short: "e",
				},
				{
					name: "outfile",
					type: "string",
					description: "Output file path (single-target builds only)",
					short: "o",
				},
				{
					name: "name",
					type: "string",
					description: "Binary name (defaults to package.json name or entry filename)",
					short: "n",
				},
				{
					name: "minify",
					type: "boolean",
					// No default: deno builds must distinguish an explicit --minify (error)
					// from the implicit bun/node default (true, applied below).
					description: "Minify the output (default for bun and node; unsupported for deno)",
				},
				{
					name: "runtime",
					type: "string",
					choices: BUILD_RUNTIMES,
					description: "Build runtime (overrides package.json crust.runtime; defaults to bun)",
				},
				{
					name: "target",
					type: "string",
					multiple: true,
					description: "Canonical compiler target(s). Omit to build all platforms for Bun or Deno.",
					short: "t",
				},
				{
					name: "outdir",
					type: "string",
					description: "Output directory for build artifacts",
					default: "dist",
					short: "d",
				},
				{
					name: "resolver",
					type: "string",
					description: "Filename for the resolver script (multi-target builds, no extension)",
					default: "cli",
					short: "r",
				},
				{
					name: "validate",
					type: "boolean",
					description:
						"Materialize command definitions before compiling; --no-validate also skips Extension build hooks",
					default: true,
				},
				{
					name: "env-file",
					type: "string",
					multiple: true,
					description: "Explicit env file(s) used for build-time constants; repeatable",
				},
				{
					name: "package",
					type: "boolean",
					description: "Stage per-platform Bun npm packages in dist/npm",
					default: false,
				},
				{
					name: "stage-dir",
					type: "string",
					description: "Directory to stage npm packages into when using --package",
					default: "dist/npm",
				},
			)
			.action(async ({ flags }) => {
				const cwd = process.cwd();
				const runtime = resolveBuildRuntime(cwd, flags.runtime);
				const entryPath = resolve(cwd, flags.entry);
				const envFiles = resolveEnvFilePaths(cwd, flags["env-file"]);

				if (!existsSync(entryPath)) {
					throw new Error(
						`Entry file not found: ${entryPath}\n  Specify a valid entry file with --entry <path>`,
					);
				}

				if (flags.package && runtime === "deno") {
					throw new Error(
						"--package does not yet support Deno builds.\n  Deno per-platform npm staging is reserved for a follow-up; build a specific target without --package for now.",
					);
				}
				if (flags.package && runtime === "node") {
					throw new Error(
						"--package does not apply to Node builds.\n  Publish the generated JavaScript artifact as a normal npm package.",
					);
				}
				if (flags.package && flags.outfile) {
					throw new Error(
						"--outfile cannot be used with --package.\n  Use --stage-dir to control the staged npm output directory.",
					);
				}
				if (runtime === "node" && flags.target?.length) {
					throw new Error(
						"--target cannot be used with --runtime node.\n  Node builds produce one portable JavaScript artifact.",
					);
				}
				if (runtime === "deno" && flags.minify) {
					throw new Error(
						"--minify is not supported with --runtime deno.\n  deno compile has no minification step; drop the flag.",
					);
				}
				if (runtime === "deno" && envFiles.length > 0) {
					throw new Error(
						"--env-file is not supported with --runtime deno.\n" +
							"  deno compile embeds every variable from the file into the binary — secrets included —\n" +
							"  with no PUBLIC_* filter. Load configuration at runtime instead (e.g. deno run --env-file).",
					);
				}
				// deno compile has no minifier; bun/node bundling minifies unless --no-minify.
				const minify = runtime === "deno" ? false : (flags.minify ?? true);

				const bunTargets = runtime === "bun" ? resolveTargets(flags.target) : undefined;
				const denoTargets = runtime === "deno" ? resolveDenoTargets(flags.target) : undefined;
				const targetCount = bunTargets?.length ?? denoTargets?.length ?? 0;
				if (!flags.package && flags.outfile && targetCount > 1) {
					throw new Error(
						"--outfile cannot be used when building for multiple targets.\n  Use --name to set the base binary name instead.",
					);
				}

				const outDir = flags.outfile
					? dirname(resolve(cwd, flags.outfile))
					: resolve(cwd, flags.outdir);
				const prepared = flags.validate
					? await buildEntrypoint(entryPath, outDir, envFiles)
					: undefined;

				if (flags.package) {
					const { runDistributeBuild } = await import("../utils/distribute.ts");
					await runDistributeBuild({
						cwd,
						entry: flags.entry,
						name: flags.name,
						minify,
						target: flags.target,
						stageDir: flags["stage-dir"],
						envFiles,
						artifactOutDir: prepared ? outDir : undefined,
					});
					return;
				}

				if (runtime === "node") {
					const outfilePath = resolveNodeOutfile(
						flags.outfile,
						flags.name,
						entryPath,
						cwd,
						flags.outdir,
					);
					console.log(`Building ${dim(entryPath)} ${cyan("→")} ${dim(outfilePath)}...`);
					await execNodeBuild(entryPath, outfilePath, minify, envFiles);
					console.log(`${green("✓")} Built successfully: ${outfilePath}`);
					return;
				}

				if (bunTargets) {
					await buildBinaryOutputs({
						entryPath,
						outfile: flags.outfile,
						name: flags.name,
						cwd,
						outdir: flags.outdir,
						resolver: flags.resolver,
						targets: bunTargets,
						envFiles,
						getFilename: getBinaryFilename,
						execute: (entry, outfile, target, files) =>
							execBuild(entry, outfile, minify, target, files),
						writeResolver,
					});
					return;
				}

				if (denoTargets) {
					await buildBinaryOutputs({
						entryPath,
						outfile: flags.outfile,
						name: flags.name,
						cwd,
						outdir: flags.outdir,
						resolver: flags.resolver,
						targets: denoTargets,
						envFiles,
						getFilename: getDenoBinaryFilename,
						execute: (entry, outfile, target) => execDenoBuild(entry, outfile, target),
						writeResolver: writeDenoResolver,
					});
				}
			}),
);
