import {
	chmodSync,
	cpSync,
	existsSync,
	mkdirSync,
	mkdtempSync,
	readdirSync,
	readFileSync,
	rmSync,
	symlinkSync,
	writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { checkPackage, createPackageFromTarballData } from "@arethetypeswrong/core";
import { defineExtensionId } from "@crustjs/core";
import { which } from "@crustjs/utils/process";
import { publint } from "publint";
import { formatMessage } from "publint/utils";
import { afterAll, afterEach, beforeAll, describe, expect, it } from "vite-plus/test";

import crustPackage from "../package.json";
import { build, type BuildResult } from "../src/index.ts";
import { BUN_TARGETS } from "../src/utils/build-helpers.ts";
import { reapBoundedProcesses, runBoundedProcess } from "./bounded-process.ts";
import { hostTarget } from "./helpers.ts";

/**
 * The published `@crustjs/crust` root package is generated by `crust build`
 * from `dist/` (`vp pack`) plus `exports` carried from package.json. This stages a
 * Node-runtime stand-in with the real `dist/` and `exports` — the root package
 * layout without compiling crust's own binaries — and checks it the way a
 * consumer meets it: publint, attw, and `import { build } from "@crustjs/crust"`
 * under Node with bun on PATH.
 */
const packageDir = resolve(import.meta.dirname, "..");
const repoRoot = resolve(packageDir, "..", "..");
const corePath = fileURLToPath(import.meta.resolve("@crustjs/core"));
const coreDir = resolve(repoRoot, "packages", "core");
const host = hostTarget();
const nodePath = which("node");

const root = mkdtempSync(join(tmpdir(), "crust-library-"));
const distDir = join(root, "dist");
const libraryProject = join(root, "library");
const stagedRoot = join(libraryProject, ".crust", "root");
const consumer = join(root, "consumer");
const app = join(root, "app");
let tarball: Uint8Array;

function readJson<T>(path: string): T {
	return JSON.parse(readFileSync(path, "utf8")) as T;
}

beforeAll(async () => {
	if (host === null) throw new Error("This test compiles for the host, which has no Bun target.");
	if (!nodePath)
		throw new Error("This test runs the published library under node, which is not on PATH.");

	const library = await runBoundedProcess(
		join(repoRoot, "node_modules", ".bin", "vp"),
		["pack", "--out-dir", distDir],
		{ cwd: packageDir, timeout: 50_000 },
	);
	expect(library.exitCode, library.stderr).toBe(0);

	mkdirSync(join(libraryProject, "src"), { recursive: true });
	writeFileSync(join(libraryProject, "src", "cli.ts"), 'console.log("stub crust");\n');
	writeFileSync(
		join(libraryProject, "package.json"),
		JSON.stringify({
			name: crustPackage.name,
			version: "0.0.0-test",
			description: crustPackage.description,
			license: crustPackage.license,
			type: "module",
			bin: { crust: "src/cli.ts" },
			crust: { runtime: "node", include: ["dist"] },
			exports: crustPackage.exports,
			peerDependencies: crustPackage.peerDependencies,
		}),
	);
	cpSync(distDir, join(libraryProject, "dist"), { recursive: true });
	await build({ cwd: libraryProject, validate: false });

	const pack = await runBoundedProcess(which("bun")!, ["pm", "pack", "--destination", root], {
		cwd: stagedRoot,
		timeout: 50_000,
	});
	expect(pack.exitCode, pack.stderr).toBe(0);
	const tgz = readdirSync(root).find((name) => name.endsWith(".tgz"));
	if (!tgz) throw new Error(`bun pm pack wrote no tarball to ${root}`);
	tarball = new Uint8Array(readFileSync(join(root, tgz)));

	// A packaged consumer: the staged root beside the core peer it declares.
	mkdirSync(join(consumer, "node_modules", "@crustjs"), { recursive: true });
	cpSync(stagedRoot, join(consumer, "node_modules", "@crustjs", "crust"), { recursive: true });
	symlinkSync(coreDir, join(consumer, "node_modules", "@crustjs", "core"), "dir");
	writeFileSync(join(consumer, "package.json"), JSON.stringify({ type: "module" }));
}, 60_000);

afterEach(reapBoundedProcesses);

// beforeAll's children are reaped before the fixture root goes.
afterAll(async () => {
	await reapBoundedProcesses();
	rmSync(root, { recursive: true, force: true });
});

describe("carried CommonJS exports", () => {
	it.each(["commonjs", undefined])(
		"rejects an unscoped .js export with source type %s",
		async (type) => {
			const project = join(root, `commonjs-${type ?? "omitted"}`);
			mkdirSync(join(project, "dist", "nested"), { recursive: true });
			mkdirSync(join(project, "src"));
			writeFileSync(join(project, "src", "cli.ts"), 'console.log("cli works");\n');
			writeFileSync(
				join(project, "dist", "nested", "index.js"),
				"module.exports = { value: 1 };\n",
			);
			const pkg = {
				name: "commonjs-cli",
				version: "0.1.0",
				type,
				bin: { "commonjs-cli": "src/cli.ts" },
				crust: { runtime: "node", include: ["dist"] },
				exports: "./dist/nested/index.js",
			};
			writeFileSync(join(project, "package.json"), JSON.stringify(pkg));
			const consume = 'import lib from "commonjs-cli"; console.log(lib.value);';
			const before = await runBoundedProcess(nodePath!, ["--input-type=module", "-e", consume], {
				cwd: project,
				timeout: 4_000,
			});
			expect(before.exitCode, before.stderr).toBe(0);
			expect(before.stdout.trim()).toBe("1");

			await expect(build({ cwd: project, validate: false })).rejects.toThrow(
				"would change module format",
			);
			expect(existsSync(join(project, ".crust", "manifest.json"))).toBe(false);
			writeFileSync(
				join(project, "dist", "index.d.ts"),
				"declare const value: 1; export = value;\n",
			);
			writeFileSync(
				join(project, "package.json"),
				JSON.stringify({ ...pkg, exports: { types: "./dist/index.d.ts", default: pkg.exports } }),
			);
			await expect(build({ cwd: project, validate: false })).rejects.toThrow(
				'target "./dist/index.d.ts"',
			);

			// An included package scope preserves CommonJS without changing the ESM CLI scope.
			writeFileSync(join(project, "dist", "package.json"), JSON.stringify({ type: "commonjs" }));
			await build({ cwd: project, validate: false });
			const staged = join(project, ".crust", "root");
			const after = await runBoundedProcess(nodePath!, ["--input-type=module", "-e", consume], {
				cwd: staged,
				timeout: 4_000,
			});
			expect(after.exitCode, after.stderr).toBe(0);
			expect(after.stdout).toBe(before.stdout);
			const cli = await runBoundedProcess(nodePath!, ["bin/commonjs-cli.js"], {
				cwd: staged,
				timeout: 4_000,
			});
			expect(cli.exitCode, cli.stderr).toBe(0);
			expect(cli.stdout.trim()).toBe("cli works");

			// An explicit extension is the alternative when there is no nested package scope.
			rmSync(join(project, "dist", "package.json"));
			writeFileSync(join(project, "dist", "index.cjs"), "module.exports = { value: 1 };\n");
			writeFileSync(
				join(project, "package.json"),
				JSON.stringify({ ...pkg, exports: "./dist/index.cjs" }),
			);
			await build({ cwd: project, validate: false });
			const explicit = await runBoundedProcess(nodePath!, ["--input-type=module", "-e", consume], {
				cwd: staged,
				timeout: 4_000,
			});
			expect(explicit.exitCode, explicit.stderr).toBe(0);
			expect(explicit.stdout).toBe(before.stdout);
		},
	);
});

describe("published @crustjs/crust library", () => {
	it("stages the library entry and carries its exports into the root package", () => {
		const staged = readJson<{ exports: unknown; files: string[]; peerDependencies: unknown }>(
			join(stagedRoot, "package.json"),
		);
		expect(staged.exports).toEqual(crustPackage.exports);
		expect(staged.peerDependencies).toEqual(crustPackage.peerDependencies);
		expect(staged.files).toEqual(["bin", "dist"]);
		for (const file of ["index.js", "index.d.ts"]) {
			expect(readFileSync(join(stagedRoot, "dist", file), "utf8")).toBe(
				readFileSync(join(distDir, file), "utf8"),
			);
		}
	});

	it("keeps BuildReport's core identity: types import @crustjs/core instead of inlining its brands", async () => {
		const dts = readFileSync(join(stagedRoot, "dist", "index.d.ts"), "utf8");
		expect(dts).toMatch(/from "@crustjs\/core"/);
		expect(dts).not.toContain("unique symbol");

		writeFileSync(
			join(consumer, "reports.ts"),
			`import type { BuildReport as CoreReport } from "@crustjs/core";
import type { BuildReport as CrustReport, BuildResult } from "@crustjs/crust";

declare const fromCore: CoreReport;
declare const fromCrust: CrustReport;
declare const result: BuildResult;
export const coreAcceptsCrust: CoreReport = fromCrust;
export const crustAcceptsCore: CrustReport = fromCore;
export const coreAcceptsResult: CoreReport | undefined = result.reports?.["cli"];
`,
		);
		const tsc = await runBoundedProcess(
			join(repoRoot, "node_modules", ".bin", "tsc"),
			[
				"--noEmit",
				"--strict",
				"--module",
				"nodenext",
				"--moduleResolution",
				"nodenext",
				"--skipLibCheck",
				"reports.ts",
			],
			{ cwd: consumer, timeout: 50_000 },
		);
		expect(tsc.exitCode, tsc.stdout + tsc.stderr).toBe(0);
	}, 60_000);

	it("passes publint", async () => {
		// The tarball is the virtual file system; its root is the package directory.
		const { messages, pkg } = await publint({
			pack: { tarball: tarball.buffer as ArrayBuffer },
			level: "warning",
		});
		expect(messages.map((message) => formatMessage(message, pkg))).toEqual([]);
	});

	it("passes attw for ESM consumers", async () => {
		const result = await checkPackage(createPackageFromTarballData(tarball));
		if (result.types === false) throw new Error("Package has no types");
		const problems = result.problems.filter(
			(problem) =>
				!("resolutionKind" in problem) ||
				!["node10", "node16-cjs"].includes(problem.resolutionKind),
		);
		expect(problems).toEqual([]);
		expect(result.entrypoints["."]?.resolutions["node16-esm"].resolution?.fileName).toContain(
			"dist/index.d.ts",
		);
	});

	it("builds a Crust app from node through the installed package, silently unless onLog is given", async () => {
		mkdirSync(join(app, "src"), { recursive: true });
		writeFileSync(
			join(app, "package.json"),
			JSON.stringify({ name: "installed-app", version: "0.1.0" }),
		);
		writeFileSync(
			join(app, "src", "cli.ts"),
			`import { Crust, defineExtension, defineExtensionId } from ${JSON.stringify(corePath)};\n` +
				`const hook = defineExtension(defineExtensionId("hook"), { build: () => [{ path: "man/installed-app.1", content: ".Dd" }] });\n` +
				`await new Crust("installed-app").extend(hook).action(({ stdout }) => stdout("hello from installed-app")).execute();\n`,
		);

		writeFileSync(
			join(consumer, "release.mjs"),
			`import { writeFileSync } from "node:fs";
import { build } from "@crustjs/crust";

const [cwd, resultPath, withLog] = process.argv.slice(2);
const logged = [];
const result = await build({
	cwd,
	targets: ["host"],
	...(withLog ? { onLog: (line, stream) => logged.push([line, stream]) } : {}),
});
writeFileSync(resultPath, JSON.stringify({ ...result, logged }));
`,
		);

		const silent = await runBoundedProcess(
			nodePath!,
			["release.mjs", app, join(root, "silent.json")],
			{
				cwd: consumer,
				timeout: 100_000,
			},
		);
		expect(silent.exitCode, silent.stderr).toBe(0);
		expect(silent.stdout).toBe("");
		expect(silent.stderr).toBe("");

		const resultPath = join(root, "result.json");
		const logged = await runBoundedProcess(nodePath!, ["release.mjs", app, resultPath, "log"], {
			cwd: consumer,
			timeout: 100_000,
		});
		expect(logged.exitCode, logged.stderr).toBe(0);
		const result = readJson<BuildResult & { logged: Array<[string, string]> }>(resultPath);
		const alias = BUN_TARGETS.info[host!].alias;
		const executable = result.artifacts.find((artifact) => artifact.kind === "executable");
		expect(result.stageDir).toBe(join(app, ".crust"));
		expect(executable).toEqual({
			kind: "executable",
			path: join(
				app,
				".crust",
				alias,
				"bin",
				`installed-app-${host}${host!.includes("windows") ? ".exe" : ""}`,
			),
			command: "installed-app",
			target: host!,
		});
		expect(result.reports).toEqual({
			"installed-app": {
				extensions: [{ id: defineExtensionId("hook"), files: ["man/installed-app.1"] }],
			},
		});
		expect(existsSync(join(app, ".crust", "root", "man", "installed-app.1"))).toBe(true);
		expect(result.logged.map(([line]) => line).join("\n")).toContain(
			"Preparing Command Snapshot for installed-app...",
		);
		expect(result.logged.every(([, stream]) => stream === "stdout")).toBe(true);

		chmodSync(executable!.path, 0o755);
		const run = await runBoundedProcess(executable!.path, [], { cwd: app, timeout: 100_000 });
		expect(run.stdout.trim()).toBe("hello from installed-app");
	}, 120_000);
});
